### ISSUE TITLE
Issue about new FreeSurferPipeline

### ISSUE THREAD

**Issue by QunjunLIANG** [Washington-University/HCPpipelines#100]
Dear experts,

Environment: HCP Pipeline v4.0.0, FreeSurfer v6.0.0, Ubuntu 14.04

I recently used the FreeSurfer pipeline to preprocess my data while an error came out.
`FreeSueferPipeline.sh: ABORTING: unrecognized option: --printcom=`

But when I have switched the pipeline utility to FreeSurfer-5.3.0, it worked without this error.

What should I do to fix this issue?

**Comment by glasserm** [comment]
Best to ask this on hcp-users@humanconnectome.org where we provide support for users.  This is mainly for development issues.

**Comment by tbbrown** [comment]
* Reopening as record of issue related to a bugfix.
* Fix this bug/issue by removing `--printcom=` flag from example script: `FreeSurferPipelineBatch.sh`

**Comment by mharms** [comment]
Closing this issue, as it now appears to be resolved.

**Comment by betsy1226** [comment]
Have you solved problem? I met the same problem, while removing --printcom= flag from FreeSurferPipelineBatch.sh seemed not worked.

**Comment by coalsont** [comment]
Please make sure you are using the latest release.
