### ISSUE TITLE
Error: Spin echo fieldmap has different dimensions than scout image, this requires a manual fix

### ISSUE THREAD

**Issue by Indusjazz** [Washington-University/HCPpipelines#102]
HI,
**Still a newbie on the use of HCP pipelines, please excuse any trivial question/comment**
I'm currently attempting to run a fMRIVolume pipeline on an fMRI dataset using spin echo field maps (AP - PA). This pipeline worked fine the very first time I ran it, but now it stops running when calling for the TopupPreprocessingAll.sh, with the following error:

Error: Spin echo fieldmap has different dimensions than scout image, this requires a manual fix.

A more complete version of the report is:

Wed Apr 10 15:44:04 EDT 2019 - MotionCorrection.sh: Change names of all matrices in OutputMotionMatrixFolder
Wed Apr 10 15:44:07 EDT 2019 - MotionCorrection.sh: Run the Derive function to generate appropriate regressors from the par file
Wed Apr 10 15:44:30 EDT 2019 - MotionCorrection.sh: END
Wed Apr 10 15:44:30 EDT 2019 - GenericfMRIVolumeProcessingPipeline.sh: EPI Distortion Correction and EPI to T1w Registration
Wed Apr 10 15:44:30 EDT 2019 - GenericfMRIVolumeProcessingPipeline.sh: mkdir -p /Users/nib19005/Desktop/2019/TMS/BIDS/TMS_BIDS3/Bids/01/MotorLoc_AP/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased
Wed Apr 10 15:44:32 EDT 2019 - DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh: START
Wed Apr 10 15:44:32 EDT 2019 - TopupPreprocessingAll.sh: START: Topup Field Map Generation and Gradient Unwarping
Wed Apr 10 15:44:32 EDT 2019 - TopupPreprocessingAll.sh: Error: Spin echo fieldmap has different dimensions than scout image, this requires a manual fix

Been looking up for similar issues in the past but couldn't find any. I have run the PreFreeSurfer, FreeSurfer and PostFresurfer pipelines before on the structural images. 

Been thinking about changing the field map size myself, but still wonder why things worked in the past and not anymore. I'm willing to share whatever bit of code/data might be helpful to figure out the issue, but I prefer to wait until you tell me what you need exactly. 

Thanks!
Nicolas

**Comment by glasserm** [comment]
This kind of question is better addressed on the hcp-users@humanconnectome.org mailing list, rather than the HCP Pipelines development website.
