### ISSUE TITLE
Why are these commented out?

### ISSUE THREAD

**Issue by glasserm** [Washington-University/HCPpipelines#114]
https://github.com/Washington-University/HCPpipelines/blob/a81844e81e631901d3495558b052ffda3a25a896/ICAFIX/hcp_fix_multi_run#L508
https://github.com/Washington-University/HCPpipelines/blob/a81844e81e631901d3495558b052ffda3a25a896/ICAFIX/ReApplyFixMultiRunPipeline.sh#L757

**Comment by mharms** [comment]
Because you didn't want to delete the individual run hp'ed time series, so that they would be available without needing to be regenerated for downstream scripts.

**Comment by glasserm** [comment]
That applied only to the concatenated files and resting state stats, unless I am forgetting something.
