### ISSUE TITLE
Variable naming ambiguity in TopupPreprocessingAll.sh

### ISSUE THREAD

**Issue by studentism** [Washington-University/HCPpipelines#119]
https://github.com/Washington-University/HCPpipelines/blob/e8eab276a3c2557f31ccc36e83620256844544a3/global/scripts/TopupPreprocessingAll.sh#L338-L340

The Pre-FreeSurfer processing pipeline sets `DistortionCorrectionFieldOutput=${StudyFolder}/${Subject}/T2w/T2wToT1wDistortionCorrectAndReg/FieldMap` when TopupPreprocessingAll.sh runs. That's meant to be a file name. However, the script's working directory is set to the same value.

Commit 23fe15f reveals the issue--the above imcp command fails because it tries to copy `T2wToT1wDistortionCorrectAndReg/FieldMap/TopupField.nii.gz` to itself (rather than to `T2wToT1wDistortionCorrectAndReg/FieldMap.nii.gz`).

The arguably "correct" fix requires a few changes, but simply reverting the second parameter back to `${DistortionCorrectionFieldOutput}.nii.gz` is enough to get the pipeline running to completion again.

**Comment by mharms** [comment]
Thanks for reporting this.  Is `${DistortionCorrectionFieldOutput}` the only case at the end of the script in this situation -- i.e., in which the `imcp` is changing the name of the file, and the name of the desired NIFTI (without extension) conflicts with an existing directory name?

**Comment by studentism** [comment]
Yes, sir, that's the only conflict. 

I added ".nii.gz" to get things running again for a deadline, but I can submit a pull request with a more elegant fix later this week if that would be helpful.

**Comment by glasserm** [comment]
Well, Tim and I aren't big fans of the no extension FSL behavior anyway.  It is perfectly fine to have Folders and files with the same name but different extensions...

**Comment by coalsont** [comment]
I would be inclined to use a convention of always specifying the file extension, even to FSL tools where it may not be necessary.  It may also be a good idea for the pipelines setup script to set FSLOUTPUTTYPE to avoid possible surprises from oddball setups.

**Comment by mharms** [comment]
I'm not a fan of that, as (1) it clutters up the code a lot, and (2) if someone wanted to use FSLOUTPUTTYPE to save as .nii rather than .nii.gz, why should we stop them?

**Comment by coalsont** [comment]
If someone changes the fsl output type, *every* wb_command using an fsl volume output will immediately break.  Trying to support this in the HCP scripts would be a nightmare.

Specifying the real filename, and not just a part of it, is more obvious to me, isn't really much "clutter" at all, and apparently would have avoided this error.

**Comment by coalsont** [comment]
In case you aren't aware: there are only two options for FSL output type that workbench can currently read at all, .nii.gz and .nii - workbench does not support analyze or nifti pair (and there does not appear to be any good reason to add support).  Workbench requires that you specify the whole filename (which includes the extension), so when the scripts say .nii.gz, but FSL generates .nii, you will get "file not found".  Trying to support uncompressed .nii in the pipelines would not only massively waste disk space, but will further clutter the scripts by requiring something like ".$volext" on the end of *every* volume file that comes from fsl when used with wb_command, instead of ".nii.gz".

**Comment by glasserm** [comment]
I would be happy with .nii.gz only for the HCP Pipelines.

**Comment by coalsont** [comment]
The point is more that the pipelines currently only support .nii.gz for any internal volume files, so it would be good to make sure FSL doesn't produce something else during the pipelines.

I have some other edits in progress on the setup script in relation to something else, so I'll add this.

**Comment by mharms** [comment]
Resolved with 8e53e151f2
