### ISSUE TITLE
Level3 .fsf pipelines

### ISSUE THREAD

**Issue by KevinAquino** [Washington-University/HCPpipelines#127]
Hi all,

I was wondering if the level 3 .fsf pipelines will be released in this repo? I would like to replicate some of the HCP findings, particularly the task related results in "Using temporal ICA to selectively remove global noise while preserving global signal in functional MRI data." 

I have found https://github.com/Washington-University/HCPpipelines/blob/e60eb03aa106cc4cb57da8cbb78fc178889583a8/TaskfMRIAnalysis/TaskfMRILevel3.sh within the repo, but its 6 years old and I imagine a lot has changed since then!

**Comment by coalsont** [comment]
I don't know the definitive state of this, but apparently the script got moved to a different branch of the repo for whatever reason:

https://github.com/Washington-University/HCPpipelines/tree/level3-task-fmri-analysis/TaskfMRIAnalysis

**Comment by KevinAquino** [comment]
Cool! thanks Tim!

**Comment by mharms** [comment]
Hi,
Yes, our internal version has definitely changed, but needs some work to be appropriate for public distribution.  Plus, we mostly recommend using PALM for Level3 (group) analyses anyway.

Cheers,
-MH

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Associate Professor of Psychiatry
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                          Email: mharms@wustl.edu

**Comment by KevinAquino** [comment]
Great! 

I had a look at: https://store.humanconnectome.org/courses/2018/exploring-the-human-connectome.php and the tutorial seems to explain the steps quite nicely! (really great write up in the pdf!) 

Out of interest while I have both of you - in the manuscript (tICA) the analysis of the task fMRI at group level looks like it is using PALM for group analysis. However there is no explanation if any covariates were taken into account (when taking 100 subsets with 28 subjects), is this true or have I missed something! thanks!

**Comment by glasserm** [comment]
We did not use PALM for this analysis, but rather a version of this level 3 script.

**Comment by KevinAquino** [comment]
Great thanks @glasserm ! Is there anything special about the level3 design template? Although I can find the templates for the level 3 analysis, the .fsf files are not in repository thanks!

**Comment by glasserm** [comment]
[design_template449.txt](https://github.com/Washington-University/HCPpipelines/files/3532645/design_template449.txt)

You have to manually edit it to the correct number of subjects.

**Comment by KevinAquino** [comment]
Great thank you for that!
