### ISSUE TITLE
FreeSurferPipeline.sh Error: could not open file No such file or directory mri_em_register: could not open GCA /usr/local/freesurfer/average/RB_all_2008-03-26.gca.

### ISSUE THREAD

**Issue by Rohit200792** [Washington-University/HCPpipelines#128]
Hi Team,

I am having trouble putting together the compatible versions of the HCPpipeline release and freesurfer.

I first tried with HCPpipelines-4.0.1 and freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c but I got the following error 
Error in FreeSurfer processing "recon-all.v6.hires: command not found"

So I looked into some discussion threads on hcp-users@humanconnectome.org/ and switched to v3.26.0 which should be independent of FreeSurfer v6 specific changes. However now I get the following issue:

100307
About to use fsl_sub to queue or run /home/rohit/HCP_PIPELINE/HCPpipelines-3.26.0/FreeSurfer/FreeSurferPipeline.sh
GCAread(/usr/local/freesurfer/average/RB_all_2008-03-26.gca): could not open file
No such file or directory
mri_em_register: could not open GCA /usr/local/freesurfer/average/RB_all_2008-03-26.gca.

The current freesurfer version downloaded [here]**(http://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall/)**  includes RB_all_2016-05-10.vc700.gca and not 2008-03-26.gca.

For more details I have attached log file
[FreeSurferPipeline.sh-o206651.txt](https://github.com/Washington-University/HCPpipelines/files/3585710/FreeSurferPipeline.sh-o206651.txt)

It would be great if you could share the correct versions of freesurfer and the HCPpipeline release that are compatible since I seem to be ending up with the wrong ones again and again.

I am using OS CentOS Linux release 7.6.1810 (Core) .

Thanks and Regards,
Rohit

**Comment by mharms** [comment]
The pipelines for v4.0.1 (and 4.0.0) are self-contained as regards “recon-all.v6.hires”.  You may have gotten a warning alerting you that the PATH would be modified to use the version that the pipelines supply, but it shouldn’t have been an “error”.

Please stick with using v.4.0.1, and FS v6, and provide the full stdout if that doesn’t work.

Cheers,
-MH

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Associate Professor of Psychiatry
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                          Email: mharms@wustl.edu

**Comment by Rohit200792** [comment]
Thank you for the assistance. As you rightly pointed out, the error was due to something else. I was able to and I was able to work around that after looking at the log more carefully. Thanks again!

Regards,
Rohit
