### ISSUE TITLE
MSMBINDIR="${HOME}/pipeline_tools/MSM"

### ISSUE THREAD

**Issue by RuneEikeland** [Washington-University/HCPpipelines#131]
Dear All,

I am using the HCP preprocessing pipeline, and I am unsure about where I should direct the path export MSMBINDIR="${HOME}/pipeline_tools/MSM"  in  GenericfMRIVolumeProcessingPipelineBatch.sh, or what I should have installed in that folder.

Best,
Rune Eikeland

**Comment by glasserm** [comment]
Please see point #6 here: https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions 

This forum is probably best used for questions related to HCP Pipelines software development.  For Usage questions, the hcp-users@humanconnectome.org mailing list is better.
