### ISSUE TITLE
Need a mechanism to identify incomplete spatial coverage in fMRI data.

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#132]
Incomplete spatial coverage is going to be a bigger problem for HCP-D/A (and some of the CRHDs) than HCP-YA (i.e., due to participants moving out the coil).  I suggest that we create some mechanism to check for this conveniently.  I'm thinking that we could write the fraction of non-zero grayordinates to a text file (as part of `fMRISurface`).  We could do the same thing for the fraction of voxels relative to the MNI template brain mask (as part of `fMRIVolume`).  Thoughts?

**Comment by glasserm** [comment]
Incomplete grayordinates coverage is not really supported (i.e. some later pipelines will fail if this is present), it must be dilated away or the subject excluded.

**Comment by mharms** [comment]
For now at least, we need a convenient way to identify these subjects.  I'll proceed with assembling a PR along the lines of what I suggested above.

**Comment by glasserm** [comment]
Sounds good.

**Comment by mharms** [comment]
Resolved with PR #138.
