### ISSUE TITLE
issues with postFreesurfer script 

### ISSUE THREAD

**Issue by rosella1234** [Washington-University/HCPpipelines#169]
Running this script gives the following error:
biolab@rocco:~/HCP/HCPpipelines-3.19.0/Examples/Scripts$ ./PostFreeSurferPipelineBatch.sh
This script must be SOURCED to correctly setup the environment prior to running any of the other HCP scripts contained here

100307
About to use fsl_sub to queue or run /home/biolab/HCP/HCPpipelines-3.19.0/PostFreeSurfer/PostFreeSurferPipeline.sh
mghRead(/home/biolab/HCP/100307/T1w/100307/mri/brain.finalsurfs.mgz, -1): could not open file
mghRead(/home/biolab/HCP/100307/T1w/100307/mri/brain.finalsurfs.mgz, -1): could not open file
mghRead(/home/biolab/HCP/100307/T1w/100307/mri/brain.finalsurfs.mgz, -1): could not open file
Image Exception : #63 :: No image files match: /home/biolab/HCP/100307/T1w/wmparc_1mm
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /home/biolab/HCP/100307/T1w/wmparc_1mm
/home/biolab/HCP/HCPpipelines-3.19.0/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh: line 80: 29885 Aborted                 fslmaths "$T1wFolder"/wmparc_1mm.nii.gz -bin -dilD -dilD -dilD -ero -ero "$T1wFolder"/"$T1wImageBrainMask"_1mm.nii.gz
set -- --path=/home/biolab/HCP       --subject=100307       --surfatlasdir=/home/biolab/HCP/HCPpipelines-3.19.0/global/templates/standard_mesh_atlases       --grayordinatesdir=/home/biolab/HCP/HCPpipelines-3.19.0/global/templates/91282_Greyordinates       --grayordinatesres=2       --hiresmesh=164       --lowresmesh=32       --subcortgraylabels=/home/biolab/HCP/HCPpipelines-3.19.0/global/config/FreeSurferSubcorticalLabelTableLut.txt       --freesurferlabels=/home/biolab/HCP/HCPpipelines-3.19.0/global/config/FreeSurferAllLut.txt       --refmyelinmaps=/home/biolab/HCP/HCPpipelines-3.19.0/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii       --regname=FS       --printcom=
. /home/biolab/HCP/HCPpipelines-3.19.0/Examples/Scripts/SetUpHCPPipeline.sh

**Comment by glasserm** [comment]
Better to ask these questions on the HCP-Users mailing list.  When you post there, please note if you successfully ran PreFreeSurfer and FreeSurfer pipelines.
