### ISSUE TITLE
Field map less distortion correction

### ISSUE THREAD

**Issue by shilpitju** [Washington-University/HCPpipelines#177]
Hi,

I have a legacy MR dataset that I want to process using HCP pipelines. Is there a way that field-map less distortion correction be carried out?

Thanks

**Comment by glasserm** [comment]
We don't currently have an implementation for this that clearly out performs no correction at all (there are folks who have claimed to do this, but they have not shown convincing evidence of this in my opinion).

**Comment by shilpitju** [comment]
Thanks so much.
