### ISSUE TITLE
split_parts_gpu with FSL6.0.1

### ISSUE THREAD

**Issue by seidern** [Washington-University/HCPpipelines#179]
When running bedpostx_gpu on CHPC with FSL6.0.1 loaded, get the following error in preproc. The problem is the command split_parts_gpu, it's fix is below.

split_parts_gpu. Wrong number of parameters
Usage:
split_parts_gpu  Datafile  Maskfile   bvals_file   bvecs_file  Grad_file(can be null)  Use_grad_file(0 or 1)  TotalNumParts  OutputDirectory

Old command (lines 324 and 326, 326 shown): 
pre_command="$FSLDIR/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask NULL 0 $njobs ${subjdir}.bedpostX"

Fixed command, added path to bvals and bvecs file:
pre_command="$FSLDIR/bin/split_parts_gpu ${subjdir}/data ${subjdir}/nodif_brain_mask ${subjdir}/bvals ${subjdir}/bvecs NULL 0 $njobs ${subjdir}.bedpostX"

**Comment by glasserm** [comment]
If you stage this as a pull request and have tested it, we can merge it.

Thanks.

**Comment by mharms** [comment]
Closing.  If you have a PR, we can re-open.
