### ISSUE TITLE
Error in FreeSurferPipelineBatch.sh

### ISSUE THREAD

**Issue by Freeman0922** [Washington-University/HCPpipelines#180]
Hi experts!

Now I am trying to preform FreeSurferPipelineBatch.sh using the example data '100307' file
downloaded from HCP website. However, error messages as follow were shown and it did not work. Is there anyone who suggest any comments?
My Freesurfer version is 7.1.0.

Thank you.

T.I.

FreeSurferPipeline.sh: line 79: tkregister: command not found

**Comment by coalsont** [comment]
Besides that error, we have not yet found a way to get freesurfer 7 to place the surfaces in our data with the accuracy we get from freesurfer 6.  Please use freesurfer 6 for now.

**Comment by Freeman0922** [comment]
Thank you.
I will try again using freesurfer 6.

**Comment by Freeman0922** [comment]
It still does not work with the following message if I already performed using freesurfer version 6.
'ERROR: recon-all command failed with return_code 1'
I do not know why this script does not complete if I used only sample example data downloaded from the HCP website.

T.I.

**Comment by glasserm** [comment]
You would need to start fresh on a subject, not rerun when you have already rerun FreeSurfer.

**Comment by Freeman0922** [comment]
Thank you. 
After using fresh dataset, it seems to work.
However, after several hours' calculation, further error happens.
Error messages are as follows.

FreeSurferPipeline.sh line 565: 56586 Abort trap:6 mri_surf2surf......
..ERROR: mri_surf2surf command for left hemisphere failed with return code: 134 ...

Any comments are appreciated.

T.I

.

**Comment by glasserm** [comment]
What is the full recon-all file?

**Comment by Freeman0922** [comment]
The last part of the recon-all.log file is as follows.


**********************************************
Computing MAP estimate using 2252 samples...
***********************************************
dt = 5.00e-06, momentum=0.80, tol=1.00e-05
l_intensity = 1.0000
Aligning input volume to GCA...
Transform matrix
 1.09244  -0.00005  -0.01725  -11.21597;
 0.00029   1.08895   0.00385  -35.80199;
 0.01794  -0.01464   1.05772  -26.17134;
 0.00000   0.00000   0.00000   1.00000;
nsamples 2252
Quasinewton: input matrix
 1.09244  -0.00005  -0.01725  -11.21597;
 0.00029   1.08895   0.00385  -35.80199;
 0.01794  -0.01464   1.05772  -26.17134;
 0.00000   0.00000   0.00000   1.00000;
 IFLAG= -1  LINE SEARCH FAILED. SEE DOCUMENTATION OF ROUTINE MCSRCH ERROR RETURN OF LINE SEARCH: INFO= 3 POSSIBLE CAUSES: FUNCTION OR GRADIENT ARE INCORRECT OR INCORRECT TOLERANCESoutof QuasiNewtonEMA: 009: -log(p) =   -0.0  tol 0.000010
Resulting transform:
 1.09244  -0.00005  -0.01725  -11.21597;
 0.00029   1.08895   0.00385  -35.80199;
 0.01794  -0.01464   1.05772  -26.17134;
 0.00000   0.00000   0.00000   1.00000;

Thank you.

**Comment by glasserm** [comment]
My guess is there is some issue with that binary (mris_surf2surf) on Mac OS X?

**Comment by Freeman0922** [comment]
So is it difficult to complete the pipeline using Mac OS X?
Should I use Linux?

Thank you.

**Comment by glasserm** [comment]
That might work better.

**Comment by Freeman0922** [comment]
Thank you very much for your advice.

**Comment by Freeman0922** [comment]
I am performing PreFreeSurferPipelineBatch.sh using Ubuntu05 Linux operation.
But it soon fails working. The followings are the error messages.

Traceback (most recent call last):
  File "/usr/local/fsl/bin/aff2rigid", line 75, in <module>
    from numpy import *
ModuleNotFoundError: No module named 'numpy'

**Comment by mharms** [comment]
This indicates a problem of some sort with your FSL installation.

**Comment by Freeman0922** [comment]
Thank you. When commanding 'fsl', the fsl gui comes. But is it necessary to uninstall fsl and to reinstall it? The fsl version is 6.0.3 b862cdds.

**Comment by glasserm** [comment]
Perhaps you need to install the numpy python package.

**Comment by Freeman0922** [comment]
Thank you.
But I think It is already installed. 
If I command 'pip install numpy', the following message comes.

Defaulting to user installation because normal site-package is not writable. Requirement already satisfied: numpy in ...
site-packages(1.18.4).

**Comment by glasserm** [comment]
I wonder if you have multiple instances of python and FSL is not finding the correct one?

**Comment by Freeman0922** [comment]
Thank you.
Now I find that python3 finds numpy, but that python2.7 (which is maybe used by fsl) does not find numpy.

**Comment by glasserm** [comment]
Probably it will work if both have the appropriate packages.

**Comment by mharms** [comment]
If installed correctly, the usage of Python in FSL is supposed to be completely self-contained in `$FSLDIR/fslpython`
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation
That's about all I know about it.  But the point is that the usual python installation stuff should be irrelevant.

**Comment by Freeman0922** [comment]
Thank you.
If I command 'fsl', the gui works well. And when I command 'python2 fslinstaller.py -c', then it says that 'FSL is up-to-date'. Does it mean FSL is successfully installed?

**Comment by glasserm** [comment]
You may need to ask on the FSL list.  I would recommend describing how you installed FSL.

**Comment by mharms** [comment]
I don't know.  Launching the FSL GUI successfully is probably not a test of FSL's python components.  FSL List is the place for this sort of support.

**Comment by Freeman0922** [comment]
Thank you very much for your comments.
