### ISSUE TITLE
Error in PostFreeSurferBatch.sh

### ISSUE THREAD

**Issue by Freeman0922** [Washington-University/HCPpipelines#181]
Hi experts

When performing PostFreeSurferBatch.sh, the following error messages have come.
Any comments are appreciated.
Thank you
Best
T.I.
............

dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Fri Jun 26 20:47:20 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: While running '/Applications/projects/Pipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh /Applications/projects/Pipelines_ExampleData 100307 /Applications/projects/Pipelines_ExampleData/100307/T1w /Applications/projects/Pipelines_ExampleData/100307/MNINonLinear Native /Applications/projects/Pipelines_ExampleData/100307/T1w/100307 T1w_acpc_dc_restore_1mm T1w_acpc_dc_restore T2w_acpc_dc_restore /Applications/projects/Pipelines/global/templates/standard_mesh_atlases 164 32 /Applications/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/acpc_dc2standard /Applications/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/standard2acpc_dc T1w_restore T2w_restore brainmask_fs /Applications/projects/Pipelines/global/config/FreeSurferAllLut.txt /Applications/projects/Pipelines/global/templates/91282_Greyordinates 2 /Applications/projects/Pipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt MSMSulc 1':
Fri Jun 26 20:47:20 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: ERROR: 'MatrixXYZ=' command failed with return code: 134
dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Applications/freesurfer/bin/../lib/gcc/lib/libgomp.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Fri Jun 26 20:47:20 JST 2020:PostFreeSurferPipeline.sh: While running '/Applications/projects/Pipelines/PostFreeSurfer/PostFreeSurferPipeline.sh --path=/Applications/projects/Pipelines_ExampleData --subject=100307 --surfatlasdir=/Applications/projects/Pipelines/global/templates/standard_mesh_atlases --grayordinatesdir=/Applications/projects/Pipelines/global/templates/91282_Greyordinates --grayordinatesres=2 --hiresmesh=164 --lowresmesh=32 --subcortgraylabels=/Applications/projects/Pipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt --freesurferlabels=/Applications/projects/Pipelines/global/config/FreeSurferAllLut.txt --refmyelinmaps=/Applications/projects/Pipelines/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii --regname=MSMSulc --printcom=':
Fri Jun 26 20:47:20 JST 2020:PostFreeSurferPipeline.sh: ERROR: '/Applications/projects/Pipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh' command failed with return code: 134

**Comment by glasserm** [comment]
Same story as before, this is an issue between FreeSurfer binaries and your mac os.

**Comment by Freeman0922** [comment]
Thank you.

**Comment by Freeman0922** [comment]
Now I am running ./PostFreeSurferBatch.sh in UBUNTU system. However, the following error comes. 
Is there any comments about this error? Any comments are appreciated. Thank you.


reading colortable from annotation file...
colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)
reading colortable from annotation file...
colortable with 76 entries read (originally Simple_surface_labels2008.txt)

WARNING: input sphere is either unusually irregular or not centered, inspect the input

/usr/local/projects/HCPpipelines/MSM/msm: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
Wed Jul  8 14:56:52 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: While running '/usr/local/projects/HCPpipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh /usr/local/projects/Pipelines_ExampleData 100307 /usr/local/projects/Pipelines_ExampleData/100307/T1w /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear Native /usr/local/projects/Pipelines_ExampleData/100307/T1w/100307 T1w_acpc_dc_restore_1mm T1w_acpc_dc_restore T2w_acpc_dc_restore /usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases 164 32 /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/acpc_dc2standard /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/standard2acpc_dc T1w_restore T2w_restore brainmask_fs /usr/local/projects/HCPpipelines/global/config/FreeSurferAllLut.txt /usr/local/projects/HCPpipelines/global/templates/91282_Greyordinates 2 /usr/local/projects/HCPpipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt MSMSulc 1':
Wed Jul  8 14:56:52 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: ERROR: '/usr/local/projects/HCPpipelines/MSM/msm' command failed with return code: 127
Wed Jul  8 14:56:52 JST 2020:PostFreeSurferPipeline.sh: While running '/usr/local/projects/HCPpipelines/PostFreeSurfer/PostFreeSurferPipeline.sh --path=/usr/local/projects/Pipelines_ExampleData --subject=100307 --surfatlasdir=/usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases --grayordinatesdir=/usr/local/projects/HCPpipelines/global/templates/91282_Greyordinates --grayordinatesres=2 --hiresmesh=164 --lowresmesh=32 --subcortgraylabels=/usr/local/projects/HCPpipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt --freesurferlabels=/usr/local/projects/HCPpipelines/global/config/FreeSurferAllLut.txt --refmyelinmaps=/usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii --regname=MSMSulc --printcom=':
Wed Jul  8 14:56:52 JST 2020:PostFreeSurferPipeline.sh: ERROR: '/usr/local/projects/HCPpipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh' command failed with return code: 127

**Comment by Freeman0922** [comment]
Hi.
When performing PosrFreeSurferBatch.sh in Ubuntu system, the following error messages come.
Are there any comments about these errors? Any comments are appreciated.
Thank you. 

reading colortable from annotation file...
colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)
reading colortable from annotation file...
colortable with 76 entries read (originally Simple_surface_labels2008.txt)

WARNING: input sphere is either unusually irregular or not centered, inspect the input

/usr/local/projects/HCPpipelines/MSM/msm: error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory
Wed Jul  8 14:56:52 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: While running '/usr/local/projects/HCPpipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh /usr/local/projects/Pipelines_ExampleData 100307 /usr/local/projects/Pipelines_ExampleData/100307/T1w /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear Native /usr/local/projects/Pipelines_ExampleData/100307/T1w/100307 T1w_acpc_dc_restore_1mm T1w_acpc_dc_restore T2w_acpc_dc_restore /usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases 164 32 /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/acpc_dc2standard /usr/local/projects/Pipelines_ExampleData/100307/MNINonLinear/xfms/standard2acpc_dc T1w_restore T2w_restore brainmask_fs /usr/local/projects/HCPpipelines/global/config/FreeSurferAllLut.txt /usr/local/projects/HCPpipelines/global/templates/91282_Greyordinates 2 /usr/local/projects/HCPpipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt MSMSulc 1':
Wed Jul  8 14:56:52 JST 2020:FreeSurfer2CaretConvertAndRegisterNonlinear.sh: ERROR: '/usr/local/projects/HCPpipelines/MSM/msm' command failed with return code: 127
Wed Jul  8 14:56:52 JST 2020:PostFreeSurferPipeline.sh: While running '/usr/local/projects/HCPpipelines/PostFreeSurfer/PostFreeSurferPipeline.sh --path=/usr/local/projects/Pipelines_ExampleData --subject=100307 --surfatlasdir=/usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases --grayordinatesdir=/usr/local/projects/HCPpipelines/global/templates/91282_Greyordinates --grayordinatesres=2 --hiresmesh=164 --lowresmesh=32 --subcortgraylabels=/usr/local/projects/HCPpipelines/global/config/FreeSurferSubcorticalLabelTableLut.txt --freesurferlabels=/usr/local/projects/HCPpipelines/global/config/FreeSurferAllLut.txt --refmyelinmaps=/usr/local/projects/HCPpipelines/global/templates/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii --regname=MSMSulc --printcom=':
Wed Jul  8 14:56:52 JST 2020:PostFreeSurferPipeline.sh: ERROR: '/usr/local/projects/HCPpipelines/PostFreeSurfer/scripts/FreeSurfer2CaretConvertAndRegisterNonlinear.sh' command failed with return code: 127

**Comment by glasserm** [comment]
I guess you need to install the openblas library on Ubuntu.

**Comment by Freeman0922** [comment]
Thank you. I will install libopenblas-base.

**Comment by mharms** [comment]
Closing this issue for now.
