### ISSUE TITLE
Motion Correction Mask Spam

### ISSUE THREAD

**Issue by glasserm** [Washington-University/HCPpipelines#183]
https://github.com/Washington-University/HCPpipelines/blob/510fcfda7d7f2effd26702b6e87c39e32dbc0947/global/scripts/mcflirt.sh#L87

In looking through some HCP Pipelines data there is a bunch of mask spam in:

${StudyFolder}/${Subject}/${fMRIName}/MotionCorrection

Since I didn't write this code @mharms, can you propose a location for deleting these?

**Comment by mharms** [comment]
The deletion of those is supposed to happen within `mcflirt.sh` itself, at L112, but there is a bug in that line, such that none of the `${output}_mask????.nii.gz` files get identified by the `imglob` command.  That `imglob` needs to be constructed like in L108, such that L112 is instead:
```
${FSLDIR}/bin/imrm `${FSLDIR}/bin/imglob ${output}_mask????.*` ${output}_allones ${output}_ref
```

**Comment by glasserm** [comment]
Thanks.  Fixed.
