### ISSUE TITLE
TOPUP and gradient distortion correction

### ISSUE THREAD

**Issue by Freeman0922** [Washington-University/HCPpipelines#186]
I am sorry for asking such a very basic question.
When performing GenericfMRIVolumeProcerssingPipelineBAtch.sh, I tried to adopt  the 'topup' to conduct the field-map correction of the resting-state fMRI data using the both AP and PA spin-echo field-map images.
However, I also have the scanner-specific grad file for the gradient distortion correction.
In this case, should I perform both TOPUP and gradient distortion correction?
Or is it OK to perform only the 'TOPUP' ?

**Comment by glasserm** [comment]
Those are independent steps, so you can do gradient distortion correction and topup or just topup.  These are two separate kinds of distortion and the b0 homogeneity induced distortion is larger and more important than gradient nonlinearity induced distortion.

**Comment by Freeman0922** [comment]
Thank you very much.
