### ISSUE TITLE
Error in GenericfMRIVolumeProcessingPipelineBatch.sh

### ISSUE THREAD

**Issue by Freeman0922** [Washington-University/HCPpipelines#188]
Hi experts.
When performing the GenericfMRIVolumeProcessingPipelineBatch.sh, the following error messages are shown. Is there any comment about this error message? Any comments are appreciated. Thank you.
```
/usr/local/projects/HCPpipelines/global/config/coeff.grad for harmonics coeffs
Traceback (most recent call last):
  File "/usr/local/fsl/fslpython/lib/python3.7/site-packages/nibabel/volumeutils.py", line 472, in array_from_file
    offset=offset)
  File "/usr/local/fsl/fslpython/lib/python3.7/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
```

**Comment by glasserm** [comment]
What data are you running this on?  Have you ever gotten the gradient distortion correction to work?

**Comment by Freeman0922** [comment]
I use the gradient file specific to our Simens scanner. As for the gradient distortion correction related to the T1w image, I think it works. I already got the T1w_gdc.nii file.

**Comment by glasserm** [comment]
That suggests your python environment and coefficents table is okay and that there is something about the fMRI input that the code doesn't like (e.g. header doesn't match the data).  Perhaps have a look at that?

**Comment by Freeman0922** [comment]
OK. I will check that. Thank you.

**Comment by mharms** [comment]
Closing this for now.  In general, we request that debugging/usage issues be directed toward the HCP User List.
