### ISSUE TITLE
Is the areal classifier in MMP_1.0 available now 

### ISSUE THREAD

**Issue by DearBraveJohn** [Washington-University/HCPpipelines#190]
Same question to #84 Individual subject parcellation using HCP-MMP1.0 classifier,  has the areal classifier in [Glasser et al. 2016](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature18933.html) available now to the public?

**Comment by glasserm** [comment]
Not yet, will be announced on the list when available.
