### ISSUE TITLE
gradient_unwarp QA much larger than 0

### ISSUE THREAD

**Issue by casparms** [Washington-University/HCPpipelines#197]
Hi! 
I am using the HCP's gradient unwarping tools to unwarp EPI data (gradient_unwarp.py v1.2). 
I am going through the QA suggestions at the end of the script. 
The first suggestion is to check "that the image output of gradient_unwarp.py is the same as from applywarp". 
Small comment: fslview is deprecated but could still be called with fslview_deprecated. 
If I do this check, the outputs are indeed the same. 

The second suggestion is "results from fslstats should be very close to zero". 
This is **not** the case, although the images look visually well unwarped. 
I get values >2000 and >20 for different runs. 

Any advice? 
Thanks! Caspar

**Comment by glasserm** [comment]
Are the images shifted relative to eachother?

**Comment by casparms** [comment]
No, but diff_tri looks like speckled noise on every frame.

**Comment by glasserm** [comment]
What is the variance of that noise relative to the image intensities?

**Comment by casparms** [comment]
Across all frames, the values in diff_tri range between -2.0497e+03 and 2.4921e+03. 
In the corrected image, the range is 0 to 2.3247e+03. Is that what you were asking?

**Comment by glasserm** [comment]
Perhaps upload the files somewhere?

**Comment by glasserm** [comment]
Looks like the trilinear interpolation is a little different, but the gradient distortion correction is similar.  I don't remember why that little QA section is there, but I wouldn't worry about this.
