### ISSUE TITLE
Something wrong with the step 'EPI Distortion Correction and EPI to T1w Registration'

### ISSUE THREAD

**Issue by debinz** [Washington-University/HCPpipelines#200]
Hi!

Thank you for developing this awesome tool! I used this tool to process multi-modality brain data (including T1, T2, rs-fmri) of children. I had finished the structure processing. When i used 'GenericfMRIVolumeProcessingPipeline.sh' to process the rs-fmri data, i found the results of some subjects it are incorrect, one of the results is as follows
![image](https://user-images.githubusercontent.com/24296206/100236449-a833bf80-2f68-11eb-98ff-90cb5239fe55.png)

i had checked the intermediate results, and i found the 'Scout_gdc_undistorted.nii.gz'  in the folder of 'DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased/' looks incorrect. The position of the brain in the image is too close to the edge and some of the data were masked out. 
![image](https://user-images.githubusercontent.com/24296206/100236905-38720480-2f69-11eb-8950-ce1f30e3a024.png)

i also checked the previously generated images, the position of the brain in these images all looked correct. The images i had cheked are as follows.
![image](https://user-images.githubusercontent.com/24296206/100237403-dc5bb000-2f69-11eb-8523-b2f4ff9e1f50.png)

btw, the options of the command 'GenericfMRIVolumeProcessingPipeline.sh' are as follows (i used the pipeline version of 4.0.0).
![image](https://user-images.githubusercontent.com/24296206/100239068-eaaacb80-2f6b-11eb-84cf-4582026bece3.png)

Something wrong with the step 'EPI Distortion Correction and EPI to T1w Registration'. 
Can you give me some advice to fix this issue? Thank you!

Zeng

**Comment by glasserm** [comment]
Perhaps best to start with the latest version of the Pipelines?  I would not use the Legacy bias correction as this isn't accurate.  I believe there are some new options for legacy fMRI data that might help @sivcek.

**Comment by debinz** [comment]
> Perhaps best to start with the latest version of the Pipelines? I would not use the Legacy bias correction as this isn't accurate. I believe there are some new options for legacy fMRI data that might help @sivcek.

Thank you! I have tried the latest version (4.3.0-rc.2) of this tool, but the same issue still happens. I have tracked the processing and find that the problem may occur in 'epi_reg_dof' because the results generated before that are correct. Besides, this command does not take a bias field map as an option so maybe it is not the problem.

Can you give me some advice? Thank you!

Zeng

**Comment by debinz** [comment]
Thank you! I have tried the latest version (4.3.0-rc.2) of this tool, but the same issue still happens. I have tracked the processing and find that the problem may occur in 'epi_reg_dof', because the results generated before that are correct. Besides, this command does not take a bias field map as an option so maybe it is not the problem.

Can you give me some advice? Thank you!
Happy Thanksgiving!

Zeng

**Comment by glasserm** [comment]
You could try modifying this setting: [--preregistertool=<"epi_reg" (default) or "flirt">] to flirt.

**Comment by debinz** [comment]
It seems that if we use "SiemensFieldMap" as the distortion correction method, the pipeline will use 'epi_reg_dof' by default to register the single-band reference image to T1w image. I checked this info in 'DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh'.

**Comment by glasserm** [comment]
We may need someone else who wrote those additional options to weigh in then.

**Comment by mharms** [comment]
Unclear if this is a general problem, or a specific issue to this dataset. Closing.
