### ISSUE TITLE
Error in PreFreeSurferPipelineBatch.sh

### ISSUE THREAD

**Issue by Kenji-Hirose** [Washington-University/HCPpipelines#211]
Hi experts!

I ran PreFreeSurferPipelineBatch.sh and got the error shown in the attached image.

If you know anything about how to fix it, please let me know.

Thanks.

K.H.

![Error in PreFreeSurferPipelineBatch_sh](https://user-images.githubusercontent.com/64634218/117522497-be9d7700-afee-11eb-9123-191b50edc6c3.png)

**Comment by Kenji-Hirose** [comment]
Thank you for your prompt reply!
I will check the points you mentioned and try again.
 I will report the result later.

Best,

K.H.

**Comment by mharms** [comment]
Assumed resolved. Closing.
