### ISSUE TITLE
Cannot find L.roi.asc and R.roi.asc required by DiffusionTractography/RunMatrix3.sh

### ISSUE THREAD

**Issue by edshui** [Washington-University/HCPpipelines#213]
Dear Experts:

I was wondering how could I generate the L.roi.asc and R.roi.asc that are required by the RunMatrix scripts?

Your help would be much appreciated. Many thanks.

**Comment by glasserm** [comment]
I don't think we have an "official" diffusion tractography pipeline.  Probably you would be using mris_convert on something like ${StudyFolder}/${Subject}/MNINonLinear/fsaverage_LR32k/${Subject}.${Hemisphere}.atlasroi.32k_fs_LR.shape.gii.

**Comment by edshui** [comment]
Hi @glasserm , thanks so much for your swift response. Forgive my ignorance as I have just started learning the HCP pipeline. From the RunMatrix3.sh, L.roi.asc and R.roi.asc are used as a termination mask. Can I confirm then that doing "mris_convert on something like ${StudyFolder}/${Subject}/MNINonLinear/fsaverage_LR32k/${Subject}.${Hemisphere}.atlasroi.32k_fs_LR.shape.gii." would permit obtaining the said termination masks? Many thanks!

**Comment by glasserm** [comment]
Can you point me to the code you are looking at?

**Comment by edshui** [comment]
Please see below from https://github.com/Washington-University/HCPpipelines/blob/diffusion-tractography/DiffusionTractography/RunMatrix3.sh

![image](https://user-images.githubusercontent.com/568101/119682347-66cb9080-be75-11eb-97e8-58f67b398b25.png)

Many thanks!

**Comment by glasserm** [comment]
I could be related to the last lines of this code, but I didn’t write these functions: https://github.com/Washington-University/HCPpipelines/blob/diffusion-tractography/DiffusionTractography/scripts/MakeTrajectorySpace_MNI.sh 

Matt.

**Comment by mharms** [comment]
Assumed resolved. Closing.
