### ISSUE TITLE
The problem about combining AP and PA image of rsfMRI data

### ISSUE THREAD

**Issue by ManyBookmark** [Washington-University/HCPpipelines#216]
Hi, 
I am trying to analyze rsfMRI data which were acquired based on HCP protocol.
I performed structural, functional, and ICA+FIX processing without error. However, I think that the merged AP-PA image is missing around the OFC signal.
My question is... 
1) How can I combine AP and PA images? (When I used "fslmerge", I couldn't get the correct image. ) 
2) should I perform phase encoding processing again by using both AP and PA rsfMRI images after performing HCPpipeline (I learned that HCPpipeline uses both polarity fieldmap images when we perform distortion correction).

**Comment by glasserm** [comment]
I don't understand what you did with fslmerge.

**Comment by ManyBookmark** [comment]
Thank you for your reply.  I wanted to get an image that can use statistical analysis. Thus, I merged two opposite phase encoding images after ICA-FIX processing as follows; 
fslmerge -t ${subject}_AP_PA_merge.nii.gz  rfMRI_REST1_AP_hp2000_clean.nii  rfMRI_REST1_PA_hp2000_clean.nii

**Comment by glasserm** [comment]
What about the result didn't you like?

**Comment by glasserm** [comment]
AP and PA have somewhat different shaped dropout regions (leading to a region of tissue covered in one but not the other) but there is also still tissue where dropout is present in both images.

**Comment by ManyBookmark** [comment]
Thank you for reply. In this subject,  I thought the PA image have signals on around OFC like an attached image.
Thus, I thought then my scripting is wrong...
AP↓
<img width="610" alt="スクリーンショット 2021-11-11 11 26 08" src="https://user-images.githubusercontent.com/74127973/141226784-ae7c93b8-4ac7-4bf7-91ae-3df337b37591.png">
PA↓
<img width="610" alt="スクリーンショット 2021-11-11 11 26 59" src="https://user-images.githubusercontent.com/74127973/141226795-db72a330-66e4-4287-a7e0-355c10f30aac.png">

**Comment by glasserm** [comment]
This is expected.

**Comment by ManyBookmark** [comment]
Thank you for your reply. I would appreciate it if you could suggest some solutions to improve the OFC signal in this case.

**Comment by glasserm** [comment]
You can reduce dropout by not using partial fourier (if it was on), reducing TE (though this will reduce BOLD CNR), or using IPAT/GRAPPA (though this will reduce SNR).

**Comment by ManyBookmark** [comment]
Thank you for your kind reply. I will try it, and is there any work that I can do in the analysis phase to solve this problem?

**Comment by mharms** [comment]
Slice angulation (orientation) can also affect the degree of susceptibility dropout:
https://www.ncbi.nlm.nih.gov/pubmed/12814592

**Comment by ManyBookmark** [comment]
Thank you for your a lot of help. Are there any suggestions that I can do in the analysis phase to solve this? It is because some cases were already acuqired.

**Comment by mharms** [comment]
No.  This is an acquisition related issue.  You can't restore something in analysis that doesn't exist.

**Comment by ManyBookmark** [comment]
Thank you for your a lot of help!
