### ISSUE TITLE
Can't process dMRI acquisitions with an odd number of slices if using latest 'eddy' features

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#217]
`eddy` needs to know the slice timing when using advanced features such as outlier replacement (`--repol` with `--ol_type=both`) or slice-to-volume (s2v) motion correction.  This information is most conveniently provided using the `--json` option, which then reads the slice-timing info (to define the "MB-groups") from the json produced by DICOM conversion (using `dcm2niix`).

However, these features of `eddy` came after the `DiffusionPreprocessing` pipeline was originally written.  At that time, the recommendation for `topup` was to remove one slice if there was an odd number of slices (due to the assumptions built into the config file that `topup` needs). Consequently, `DiffusionPreprocessing` was written to automatically remove one slice from the dMRI data in the case of an odd number slices.  However, this leads to a crash in `eddy` if using the advanced features mentioned above.

This issue has evaded detection until now because (1) the HCP-LS dMRI acquisitions used MB4 with an even number of slices, and (2) the HCP-YA acquisitions, while using MB3 with an odd number of slices, were processed before these advanced features were available.

Notably, the FSL guidance on how to handle the situation of an odd number of slices has also changed, with the suggestion being to handle the situation of an odd number of slices by using a different config file for `topup`, rather than discarding a slice: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;6c4c9591.2002

The proposed solution is to modify `DiffusionPreprocessing` to no longer automatically discard a slice in the case of an odd number of slices (although that could potentially still be provided as an option), and instead provide an option for the user to select the config file that they want to use, per the FSL link above.

**Comment by glasserm** [comment]
This makes sense.  Also at some point we may change the default topup configs for the HCP Pipelines anyway, as we have found issues with the current ones and there is room for improvement.

**Comment by MichielCottaar** [comment]
Makes sense to me. Removing the slice removal is very straightforward (see #218). So, the main difficulty is in deciding on:
1. what to do with the topup config file? Do we want to use a different one if we have an even number of slices (as Jesper recommends) or keep the code simpler but take the performance hit when users have images with an even number of slices.
2. I'm not in favour in having slice removal as an optional flag. We have quite a lot of branching in the `DiffusionPreprocessing` pipeline already, which makes it very easy for bugs to arise if users provide a different set of options than we tested. So, it is not really in line with the goal of providing a unified, well tested pipeline. The advantage of having it as a flag would be that it would provide a decent speedup for users with both an odd number of slices *and* no interest in using any of the advanced eddy features.

**Comment by glasserm** [comment]
Could the Pipeline just check whether the slices are odd and the config has subsampling and throw an error if that occurs?  Did we have an odd number of slices for any HCP data?  If so we probably need to keep it as a flag.  If not, we could probably just switch the configs instead of removing the slices.

**Comment by MichielCottaar** [comment]
The original HCP YA data had an odd number of slices, so removing slices was used for the original processing. 

If we are just going to throw an error, I think it would make sense for topup to check and throw the error rather directly rather than try to replicate the check outside of topup. However, this would mean that the pipeline would not be able to use the advanced eddy features for any data with an odd number of slices.

**Comment by glasserm** [comment]
Then we should probably maintain the legacy behavior with a flag, but recommend folks use a different config for odd slices going forward to enable advanced eddy options.

**Comment by mharms** [comment]
I think it comes down to how much we want to maintain backwards consistency in this particular case.  If we want to maintain backwards consistency (including the ability to process the HCP-YA data the "same" way it was processed originally), then I think the default would need to remain to discard a slice if there is an odd number of slices.  In which case, we would address the deficiency by adding a flag to override that behavior combined with a flag to flag to provide an alternative config file for `topup`.

In terms of parameter checking, it would be _nice_ if we added some sanity checking of whether the image dimensions are consistent with the intended config file, as that gives us control over the error message (and returns an error more quickly).   What is the verbiage of the error message that `topup` returns in that situation?

Does @coalsont have any thoughts on how he wants to see this implemented?

**Comment by glasserm** [comment]
We only need to maintain availability with the old pathway, not force it as the default if it is not indeed the optimal approach.  We certainly have changed default behavior in the past in major ways when it was appropriate.  The goal of the HCP Pipelines is to update the default pathway with new improvements as they become available.

**Comment by mharms** [comment]
Yes, that's another option -- maintain "availability" to process by discarding a slice in the situation of an odd number of slices, but that's no longer the "default".

**Comment by MichielCottaar** [comment]
Great, I've updated #218 now to accept two new optional flags: (1) `--ensure-even-slices` for when you want to remove any odd slices (no longer the default behaviour) and (2) `--topup-config-file=<file>` to override the topup config file (default is still `${HCPPIPEDIR_Config}/b02b0.cnf`. I'm testing it now on the HCP YA data (which has an odd number of slices) and will let you know.

**Comment by mharms** [comment]
Should be resolved. Closing.
