### ISSUE TITLE
Running FAST segmentation Exception: Not enough classes detected to init KMeans

### ISSUE THREAD

**Issue by soichih** [Washington-University/HCPpipelines#220]
Hello. We are running HCPpipeline `docker://bids/hcppipelines:v4.1.3-1`. When we feed t1w and t2w input file, we run into the following error message.

```
Fri Feb 18 18:17:36 EST 2022:T2wToT1wReg.sh: START: T2w2T1Reg
Running FAST segmentation
Exception: Not enough classes detected to init KMeans
Image Exception : #63 :: No image files match: /output/sub-NDARINV0LEM88KP/T2w/T2wToT1wReg/T2w2T1w_fast_pve_2
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /output/sub-NDARINV0LEM88KP/T2w/T2wToT1wReg/T2w2T1w_fast_pve_2
/usr/local/fsl/bin/epi_reg: line 320: 13055 Aborted                 $FSLDIR/bin/fslmaths ${vout}_fast_pve_2 -thr 0.5 -bin ${vout}_fast_wmseg
Image Exception : #63 :: No image files match: /output/sub-NDARINV0LEM88KP/T2w/T2wToT1wReg/T2w2T1w_fast_wmseg
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /output/sub-NDARINV0LEM88KP/T2w/T2wToT1wReg/T2w2T1w_fast_wmseg
/usr/local/fsl/bin/epi_reg: line 329: 13086 Aborted                 $FSLDIR/bin/fslmaths ${vout}_fast_wmseg -edge -bin -mas ${vout}_fast_wmseg ${vout}_fast_wmedge
```

I think this means that FAST segmentation is failing to generate the output file `T2w2T1w_fast_pve_2` because something is not right with the input files. Is that correct? If so, do you have any suggestion on what we should do to troubleshoot this problem?

We are running the container with the following options

https://github.com/brainlife/app-hcp-pipeline/blob/v4.1.3/main

```
singularity exec -e \
    -B `pwd`/bids:/bids \
    -B `pwd`/output:/output \
    docker://bids/hcppipelines:v4.1.3-1 \
    ./run.py /bids /output participant \
    --n_cpus 8 \
    --stages $stage \
    --license_key "$FREESURFER_LICENSE" \
    --participant_label $sub \
    --processing_mode $processing_mode \
    $skipbidsvalidation
```

We are running a slightly modified version of `run.py` for our jobs and here is the current content > https://github.com/brainlife/app-hcp-pipeline/blob/v4.1.3/run.py

**Comment by glasserm** [comment]
We are not affiliated with this container and cannot support it.  The official container for the HCP Pipelines is Qu|Nex (https://qunex.yale.edu/) or you can run the HCP Pipelines outside the container.

**Comment by soichih** [comment]
Oh.. sorry! I will repost it here > https://github.com/BIDS-Apps/HCPPipelines

Thanks!
