### ISSUE TITLE
Default training in MR FIX is non-optimal

### ISSUE THREAD

**Issue by glasserm** [Washington-University/HCPpipelines#227]
https://github.com/Washington-University/HCPpipelines/blob/3a6406cc065227a45b147f2e08ce09f171de21df/ICAFIX/hcp_fix_multi_run#L745

We are currently defaulting to hp2000 SR+FIX training, when that is not optimal.  We should default to the MR+FIX training file, as that is more generic (has MR and SR FIX data, HCP-YA scanner and Prisma, rest and task).  

https://github.com/Washington-University/HCPpipelines/blob/3a6406cc065227a45b147f2e08ce09f171de21df/Examples/Scripts/IcaFixProcessingBatch.sh#L158

**Comment by glasserm** [comment]
@coalsont @mharms I think we might have just copied things over from SR+FIX without making different defaults for MR+FIX and SR+FIX.

**Comment by mharms** [comment]
If we change `hcp_fix_multi_run` now, there is a risk of users getting different behavior for the same calling options, without them knowing it.  Maybe we should add a warning instead?

**Comment by glasserm** [comment]
The current behavior is a bug and is causing problems.  I do think we should publicize the change, but we do need to make a change.

**Comment by coalsont** [comment]
Where is the MR FIX training file?

**Comment by coalsont** [comment]
Also, are you suggesting that for the batch file, when configured for SR FIX, that it should use the MR FIX training anyway, or continue to do what it does now?

**Comment by glasserm** [comment]
The MR+FIX training file is included in the FIX distribution and is named: 

fix1.06.15/training_files/HCP_Style_Single_Multirun_Dedrift.RData

It should work fine for SR+FIX too, so we could change it to be the default for everything or just MR+FIX.  Since we recommend MR+FIX in most cases, this will cover most users anyway.

**Comment by mharms** [comment]
I would leave the default for SR-FIX as it is.

**Comment by coalsont** [comment]
What would you have it do if the fix distribution is too old to have the MR training data?

**Comment by glasserm** [comment]
Error and tell them to update.

**Comment by coalsont** [comment]
This should be fixed now, though it needs to be tested.

**Comment by glasserm** [comment]
Thanks Tim
