### ISSUE TITLE
Image Exception Error running FreeSurferPipeline.sh 

### ISSUE THREAD

**Issue by margotwagner** [Washington-University/HCPpipelines#228]
I am trying to install the HCPpipeline on Linux and run it for the single subject example data provided. After following the installation instructions for all the prerequisites and the pipeline, as well as the 'Installation and Usage Instructions', I ran `PreFreeSurferPipelineBatch.sh`. It appeared to run without any problems (no error messages and the last log of `PreFreeSurferPipeline.sh: Completed!`. I then ran `FreeSurferPipelineBatch.sh` where I got the following error:

> Image Exception : #63 :: No image files match: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  No image files match: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore
> /home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/FreeSurferPipeline.sh: line 565: 32702 Aborted                 fslmaths ${T1wImage} -thr 0 ${zero_threshold_T1wImage}
> Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: While running '/home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/FreeSurferPipeline.sh --subject=100307 --subjectDIR=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w --t1=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz --t1brain=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_brain.nii.gz --t2=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T2w_acpc_dc_restore.nii.gz':
> Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: ERROR: fslmaths command failed with return_code: 134

There seems to be a file with contents stored at `home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz`, so I am confused. 

Here are the `FreeSurferPipelineBatch.sh` logs:
> ========================================
  DIRECTORY: /home/mwagner/projects/hcp/HCPPIPEDIR
    PRODUCT: HCP Pipeline Scripts
    VERSION: v4.3.0
========================================
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: FREESURFER_HOME: /home/mwagner/bin/freesurfer
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: Platform Information Follows:
Linux porter 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: We were not able to locate one of the following required tools:
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: recon-all.v6.hires, conf2hires, or longmc
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING:
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: To be able to run this script using the standard versions of these tools,
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: we added /home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/custom to the beginning of the PATH.
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING:
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: If you intended to use some other version of these tools, please configure
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: your PATH before invoking this script, such that the tools you intended to
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: use can be found on the PATH.
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING:
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: WARNING: PATH set to: /home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/custom:/home/mwagner/bin/workbench/bin_linux64:/home/mwagner/bin/fsl/bin:/home/mwagner/bin/fsl/bin:/home/mwagner/anaconda3/condabin:/home/mwagner/bin/freesurfer/bin:/home/mwagner/bin/freesurfer/fsfast/bin:/home/mwagner/bin/freesurfer/tktools:/home/mwagner/bin/freesurfer/mni/bin:/home/mwagner/bin/Blender-2.79-CellBlender:/usr/local/IMOD/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/local/bin:/usr/bin:/bin:/usr/games:/snap/bin:/var/cfengine/bin:/home/mwagner/bin/pycharm-community-2019.2.2/bin:/home/mwagner/bin/workbench/bin_linux64
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: Showing HCP Pipelines version
========================================
  DIRECTORY: /home/mwagner/projects/hcp/HCPPIPEDIR
    PRODUCT: HCP Pipeline Scripts
    VERSION: v4.3.0
========================================
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: Showing recon-all.v6.hires version
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: /home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/custom/recon-all.v6.hires
freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Mon May  9 09:27:08 PDT 2022:FreeSurferPipeline.sh: Showing tkregister version
/home/mwagner/bin/freesurfer/tktools/tkregister
stable6
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Showing mri_concatenate_lta version
/home/mwagner/bin/freesurfer/bin/mri_concatenate_lta
stable6
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Showing mri_surf2surf version
/home/mwagner/bin/freesurfer/bin/mri_surf2surf
stable6
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Showing fslmaths location
/home/mwagner/bin/fsl/bin/fslmaths
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: INFO: Determined that FreeSurfer full version string is: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: INFO: Determined that FreeSurfer version is: 6.0.0
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Using named parameters
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Subject Directory: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Subject: 100307
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: T1w Image: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: T1w Brain: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_brain.nii.gz
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Include -conf2hires flag in recon-all: TRUE
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Starting main functionality
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Retrieve positional parameters
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: SubjectDIR: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: SubjectID: 100307
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: T1wImage: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: T1wImageBrain: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_brain.nii.gz
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: T2wImage: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T2w_acpc_dc_restore.nii.gz
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: recon_all_seed:
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: flair: FALSE
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: existing_subject: FALSE
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: extra_reconall_args:
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: conf2hires: TRUE
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Figure out the number of cores to use.
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: num_cores: 8
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: Thresholding T1w image to eliminate negative voxel values
Mon May  9 09:27:09 PDT 2022:FreeSurferPipeline.sh: ...This produces a new file named: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz
/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz
/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_zero_threshold.nii.gz
Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: ERROR: fslmaths command failed with return_code: 134
Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: ABORTING

> Image Exception : #63 :: No image files match: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore
terminate called after throwing an instance of 'std::runtime_error'
  what():  No image files match: /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore
/home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/FreeSurferPipeline.sh: line 565: 32702 Aborted                 fslmaths ${T1wImage} -thr 0 ${zero_threshold_T1wImage}
Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: While running '/home/mwagner/projects/hcp/HCPPIPEDIR/FreeSurfer/FreeSurferPipeline.sh --subject=100307 --subjectDIR=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w --t1=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz --t1brain=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore_brain.nii.gz --t2=/home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T2w_acpc_dc_restore.nii.gz':
Mon May  9 09:27:10 PDT 2022:FreeSurferPipeline.sh: ERROR: fslmaths command failed with return_code: 134

Here are the logs from running `PreFreeSurferPipelineBatch.sh`:
> ========================================
  DIRECTORY: /home/mwagner/projects/hcp/HCPPIPEDIR
    PRODUCT: HCP Pipeline Scripts
    VERSION: v4.3.0
========================================
Fri May  6 13:42:10 PDT 2022:PreFreeSurferPipeline.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 13:42:10 PDT 2022:PreFreeSurferPipeline.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 13:42:10 PDT 2022:PreFreeSurferPipeline.sh: HCPPIPEDIR_Global: /home/mwagner/projects/hcp/HCPPIPEDIR/global/scripts
Fri May  6 13:42:10 PDT 2022:PreFreeSurferPipeline.sh: Platform Information Follows:
Linux porter 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
Fri May  6 13:42:10 PDT 2022:PreFreeSurferPipeline.sh: Parsing Command Line Options
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: Finished Parsing Command Line Options
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: StudyFolder: /home/mwagner/projects/hcp/Pipelines_ExampleData
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: Subject: 100307
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wInputImages: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/unprocessed/3T/T1w_MPR1/100307_3T_T1w_MPR1.nii.gz@
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wInputImages: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/unprocessed/3T/T2w_SPC1/100307_3T_T2w_SPC1.nii.gz@
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wTemplate: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_0.7mm.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wTemplateBrain: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_0.7mm_brain.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wTemplate2mm: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_2mm.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wTemplate: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T2_0.7mm.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wTemplateBrain: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T2_0.7mm_brain.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wTemplate2mm: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T2_2mm.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: TemplateMask: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_0.7mm_brain_mask.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: Template2mmMask: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_2mm_brain_mask_dil.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: BrainSize: 150
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: FNIRTConfig: /home/mwagner/projects/hcp/HCPPIPEDIR/global/config/T1_2_MNI152_2mm.cnf
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: MagnitudeInputName: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/unprocessed/3T/T1w_MPR1/100307_3T_FieldMap_Magnitude.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: PhaseInputName: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/unprocessed/3T/T1w_MPR1/100307_3T_FieldMap_Phase.nii.gz
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: GEB0InputName: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: TE: 2.46
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: SpinEchoPhaseEncodeNegative: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: SpinEchoPhaseEncodePositive: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: SEEchoSpacing: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: SEUnwarpDir: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wSampleSpacing: 0.0000074
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wSampleSpacing: 0.0000021
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: UnwarpDir: z
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: GradientDistortionCoeffs: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: AvgrdcSTRING: SiemensFieldMap
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: TopupConfig: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: BiasFieldSmoothingSigma:
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: UseJacobian: true
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wBiasCorrect:
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: CustomBrain: NONE
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: ProcessingMode: HCPStyleData
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T1wFolder: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: T2wFolder: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: AtlasSpaceFolder: /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/MNINonLinear
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/xfms/
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w/xfms/
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/MNINonLinear/xfms/
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: POSIXLY_CORRECT=
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: Processing Modality: T1w
Fri May  6 13:42:12 PDT 2022:PreFreeSurferPipeline.sh: NOT PERFORMING GRADIENT DISTORTION CORRECTION
Fri May  6 13:42:18 PDT 2022:PreFreeSurferPipeline.sh: Not Averaging T1w Images
Fri May  6 13:42:18 PDT 2022:PreFreeSurferPipeline.sh: ONLY ONE IMAGE FOUND: COPYING
Fri May  6 13:42:19 PDT 2022:PreFreeSurferPipeline.sh: Aligning T1w image to /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T1_0.7mm.nii.gz to create native volume space
Fri May  6 13:42:19 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/ACPCAlignment
Fri May  6 13:42:20 PDT 2022:ACPCAlignment.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 13:42:20 PDT 2022:ACPCAlignment.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 13:42:20 PDT 2022:ACPCAlignment.sh: START
Final FOV is:
0.000000 256.000000 0.000000 320.000000 58.000000 214.000000

> Fri May  6 13:44:08 PDT 2022:ACPCAlignment.sh: END
Fri May  6 13:44:08 PDT 2022:PreFreeSurferPipeline.sh: Performing Brain Extraction using FNIRT-based Masking
Fri May  6 13:44:08 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/BrainExtraction_FNIRTbased
Fri May  6 13:44:09 PDT 2022:BrainExtraction_FNIRTbased.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 13:44:09 PDT 2022:BrainExtraction_FNIRTbased.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 13:44:09 PDT 2022:BrainExtraction_FNIRTbased.sh: HCPPIPEDIR_Templates: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates
Fri May  6 13:44:09 PDT 2022:BrainExtraction_FNIRTbased.sh: START: BrainExtraction_FNIRT
Fri May  6 13:54:51 PDT 2022:BrainExtraction_FNIRTbased.sh: END: BrainExtraction_FNIRT
Fri May  6 13:54:51 PDT 2022:PreFreeSurferPipeline.sh: Processing Modality: T2w
Fri May  6 13:54:51 PDT 2022:PreFreeSurferPipeline.sh: NOT PERFORMING GRADIENT DISTORTION CORRECTION
Fri May  6 13:54:53 PDT 2022:PreFreeSurferPipeline.sh: Not Averaging T2w Images
Fri May  6 13:54:53 PDT 2022:PreFreeSurferPipeline.sh: ONLY ONE IMAGE FOUND: COPYING
Fri May  6 13:54:55 PDT 2022:PreFreeSurferPipeline.sh: Aligning T2w image to /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates/MNI152_T2_0.7mm.nii.gz to create native volume space
Fri May  6 13:54:55 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w/ACPCAlignment
Fri May  6 13:54:55 PDT 2022:ACPCAlignment.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 13:54:55 PDT 2022:ACPCAlignment.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 13:54:55 PDT 2022:ACPCAlignment.sh: START
Final FOV is:
0.000000 256.000000 0.000000 320.000000 60.000000 214.000000

> Fri May  6 13:56:33 PDT 2022:ACPCAlignment.sh: END
Fri May  6 13:56:33 PDT 2022:PreFreeSurferPipeline.sh: Performing Brain Extraction using FNIRT-based Masking
Fri May  6 13:56:33 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w/BrainExtraction_FNIRTbased
Fri May  6 13:56:33 PDT 2022:BrainExtraction_FNIRTbased.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 13:56:33 PDT 2022:BrainExtraction_FNIRTbased.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 13:56:33 PDT 2022:BrainExtraction_FNIRTbased.sh: HCPPIPEDIR_Templates: /home/mwagner/projects/hcp/HCPPIPEDIR/global/templates
Fri May  6 13:56:33 PDT 2022:BrainExtraction_FNIRTbased.sh: START: BrainExtraction_FNIRT
Fri May  6 14:07:07 PDT 2022:BrainExtraction_FNIRTbased.sh: END: BrainExtraction_FNIRT
Fri May  6 14:07:07 PDT 2022:PreFreeSurferPipeline.sh: Performing SiemensFieldMap Readout Distortion Correction
Fri May  6 14:07:07 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w/T2wToT1wDistortionCorrectAndReg
Fri May  6 14:07:07 PDT 2022:T2wToT1wDistortionCorrectAndReg.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 14:07:07 PDT 2022:T2wToT1wDistortionCorrectAndReg.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 14:07:07 PDT 2022:T2wToT1wDistortionCorrectAndReg.sh: HCPPIPEDIR_Global: /home/mwagner/projects/hcp/HCPPIPEDIR/global/scripts
Fri May  6 14:07:09 PDT 2022:T2wToT1wDistortionCorrectAndReg.sh: START

> FieldMapPreprocessingAll.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
FieldMapPreprocessingAll.sh: FSLDIR: /home/mwagner/bin/fsl
FieldMapPreprocessingAll.sh: HCPPIPEDIR_Global: /home/mwagner/projects/hcp/HCPPIPEDIR/global/scripts
Fri May  6 14:07:09 PDT 2022:FieldMapPreprocessingAll.sh: Field Map Preprocessing and Gradient Unwarping
Fri May  6 14:07:09 PDT 2022:FieldMapPreprocessingAll.sh: START
Loading volumes
Phase loaded
Magnitude loaded
Mask loaded
Rewrapping phase range to [-pi,pi]
Number of phase splits = 8
Calculating starting matrices (6143 by 6143)
Finished connection_matrices
18546 constraints left
8771 constraints left
6835 constraints left
5338 constraints left
3472 constraints left
1841 constraints left
192 constraints left
Did while loop 6142 times
Done. Created /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T2w/T2wToT1wDistortionCorrectAndReg/FieldMap/FieldMap for use with FEAT.
Fri May  6 14:07:15 PDT 2022:FieldMapPreprocessingAll.sh: DONE: fsl_prepare_fieldmap.sh
Fri May  6 14:07:18 PDT 2022:FieldMapPreprocessingAll.sh: Field Map Preprocessing and Gradient Unwarping
Fri May  6 14:07:18 PDT 2022:FieldMapPreprocessingAll.sh: END
Running FAST segmentation
FLIRT pre-alignment
Running BBR
0.347956 0.999981 -0.006128 0.001073 0.000000 0.006168 0.999082 -0.042399 0.000000 -0.000813 0.042404 0.999100 0.000000 -1.303270 -3.381539 6.134600 1.000000
Fri May  6 14:23:45 PDT 2022:T2wToT1wDistortionCorrectAndReg.sh: END
Fri May  6 14:23:45 PDT 2022:PreFreeSurferPipeline.sh: Performing Bias Field Correction using sqrt(T1w x T2w)
Fri May  6 14:23:45 PDT 2022:PreFreeSurferPipeline.sh: mkdir -p /home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/BiasFieldCorrection_sqrtT1wXT2w
Fri May  6 14:23:45 PDT 2022:BiasFieldCorrection_sqrtT1wXT2w.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 14:23:45 PDT 2022:BiasFieldCorrection_sqrtT1wXT2w.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 14:23:45 PDT 2022:BiasFieldCorrection_sqrtT1wXT2w.sh: CARET7DIR: /home/mwagner/bin/workbench/bin_linux64
Fri May  6 14:23:45 PDT 2022:BiasFieldCorrection_sqrtT1wXT2w.sh: START: BiasFieldCorrection
0.240758
0.975645
.8552660
Fri May  6 14:25:32 PDT 2022:BiasFieldCorrection_sqrtT1wXT2w.sh: END: BiasFieldCorrection
Fri May  6 14:25:32 PDT 2022:PreFreeSurferPipeline.sh: Creating one-step resampled version of {T1w,T2w}_acpc_dc outputs
Fri May  6 14:30:11 PDT 2022:PreFreeSurferPipeline.sh: Performing Atlas Registration to MNI152 (FLIRT and FNIRT)
Fri May  6 14:30:11 PDT 2022:AtlasRegistrationToMNI152_FLIRTandFNIRT.sh: HCPPIPEDIR: /home/mwagner/projects/hcp/HCPPIPEDIR
Fri May  6 14:30:11 PDT 2022:AtlasRegistrationToMNI152_FLIRTandFNIRT.sh: FSLDIR: /home/mwagner/bin/fsl
Fri May  6 14:30:12 PDT 2022:AtlasRegistrationToMNI152_FLIRTandFNIRT.sh: START: AtlasRegistration to MNI152
Fri May  6 14:45:32 PDT 2022:AtlasRegistrationToMNI152_FLIRTandFNIRT.sh: END: AtlasRegistration to MNI152
Fri May  6 14:45:32 PDT 2022:PreFreeSurferPipeline.sh: Completed!

**Comment by glasserm** [comment]
what do you get if you type:

ls /home/mwagner/projects/Pipelines_ExampleData/100307/T1w/T1w_acpc_dc_restore.nii.gz

In the terminal?

**Comment by margotwagner** [comment]
I didn't update the project directory correctly for all of FreeSurfer, thanks!
