### ISSUE TITLE
Error with mri_surf2surf in FreeSurferPipeline.sh

### ISSUE THREAD

**Issue by margotwagner** [Washington-University/HCPpipelines#229]
I am trying to run the FreeSurferPipelineBatch using the example data provided (subject 100307). 

Currently, I am getting an error while running `FreeSurferPipeline.sh`. 

The error is 

> Reading source surface reg /nadata/cnl/home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/100307/surf/lh.white.preaparc
No such file or directory
mri_surf2surf: could not read surface /nadata/cnl/home/mwagner/projects/hcp/Pipelines_ExampleData/100307/T1w/100307/surf/lh.white.preaparc
No such file or directory

This occurs after FreeSurferPipeline.sh calls mri_surf2surf using the following command
>`mri_surf2surf --s 100307 --hemi lh --sval-xyz white.preaparc --surfreg white.preaparc --reg transforms/rawavg2conf.dat rawavg.cmdc.mgz --tval-xyz rawavg.cmdc.mgz --tval white.preaparc.rawavg`

Generally --surfreg makes the surface, and the current `FreeSurferPipeline.sh` script states that 

> #The ?h.white.deformed surfaces are used in FreeSurfer BBR registrations for fMRI and diffusion and have been moved into the HCP's T1w space so that BBR produces a transformation containing only the minor adjustment to the registration.

There does not appear to be a file anywhere that matches "lh.white.preaparc", "*preaparc*", or "*white*". The listed surf files are lh.orig.nofix, lh.smoothwm.nofix, lh.inflated.nofix, lh.qsphere.nofix, lh.orig, lh.inflated, lh.defect_labels, lh.defect_bordered, lh.defect_chull. 

Attached is the output file.
[FreeSurferPipelineOutput.txt](https://github.com/Washington-University/HCPpipelines/files/8681789/FreeSurferPipelineOutput.txt)

**Comment by glasserm** [comment]
There doesn't seem to be a complete recon-all log in your file and it says you told it that the subject already exists.  What exactly did you try to do here?

**Comment by margotwagner** [comment]
The previous run stopped unexpectedly, so I reran it with the flag of` existing_subject="TRUE".`

Here is the output from the first run that was stopped
[FreeSurferPipelineOutputFirstRun.txt](https://github.com/Washington-University/HCPpipelines/files/8682315/FreeSurferPipelineOutputFirstRun.txt)

Here is the recon-all.log file for the most recent run 
[recon-all.log](https://github.com/Washington-University/HCPpipelines/files/8682319/recon-all.log)

**Comment by glasserm** [comment]
I would start fresh and see if it works.  I don't know that randomly stopping recon-all allows you to assume it will resume in the appropriate location.

**Comment by mharms** [comment]
The `--existing-subject` flag is for making FS edits after a successful `recon-all`.  It is not for resuming processing of a subject that failed for some reason.

**Comment by margotwagner** [comment]
Thanks, I will try that.

**Comment by mharms** [comment]
Assumed resolved.  Closing.
