### ISSUE TITLE
hcp_fix error

### ISSUE THREAD

**Issue by relyativist** [Washington-University/HCPpipelines#235]
Hi, I am trying to run hcp_fix, but have an error:

    ===> ERROR: Command returned with nonzero exit code
    ---------------------------------------------------
             script: hcp_fix
    stopped at line: 195
    call: cd 'dirname $fmri'
    expanded call: cd dirname $fmri
          exit code: 1
          

I can't get why there are no any guidance to run hcp_fix with error.
    
    Tue Sep  6 18:23:25 UTC 2022:hcp_fix: ERROR: 'cd' command failed with return code: 1

**Comment by glasserm** [comment]
This might be better addressed on the hcp-users mailing list: ﻿﻿﻿﻿﻿﻿﻿hcp-users@humanconnectome.org, where you can hopefully provide your call to the hcp_fix pipeline and info about your fMRI data.  At this point, we would generally recommend using multi-run FIX.

**Comment by coalsont** [comment]
https://github.com/Washington-University/HCPpipelines/blob/master/Examples/Scripts/IcaFixProcessingBatch.sh might help.  Note that you need to have run the earlier pipelines on your data already (all three freesurfer ones, and fMRI volume and surface).
