### ISSUE TITLE
Areal classifier from Glasser et al. 2016 

### ISSUE THREAD

**Issue by charlesincharge** [Washington-University/HCPpipelines#240]
Is the areal classifier from [Glasser et al. 2016](https://www.nature.com/articles/nature18933) available? I was hoping to use it compare our single-neuron recording locations with prior fMRI literature. 

I saw that https://github.com/Washington-University/HCPpipelines/issues/84 and https://github.com/Washington-University/HCPpipelines/issues/190 asked about this previously but wanted to check in case I had missed something. Our participants occasionally have atypical neuroanatomy, so we use preoperative fMRI to map out candidate recording locations. Was wondering if the classifier pipeline will be out soon enough for us to use / ask our participant to perform the corresponding fMRI tasks.

Thanks!

**Comment by coalsont** [comment]
Some work was done on this, but other things took priority.  It is not released, and I don't know where on the priority list it is.

**Comment by glasserm** [comment]
Any use of the HCP Pipelines for preoperative planning would best be done as a collaboration.  I have several of these ongoing, but am not sure I would want folks using them independently for this sort of thing.

**Comment by charlesincharge** [comment]
Thanks for the prompt reply! Let me check with my labmates to see if anyone has bandwidth to collaborate.

For context, we have an existing preoperative planning task/pipeline that we plan to use to specify implant locations. However, we are considering adding on the HCP task fMRI battery so that we can determine, with some confidence, how our implant location relates to fMRI studies. Determining that is less time-sensitive, but we would still want to run the HCP task fMRI battery before implanting.

I would have run this analysis mainly if it was straightforward (because I will graduate in a few months). Since it's more involved though, let me see if any of my labmates can pick this up. Thanks!
