### ISSUE TITLE
draw ROIs around vertices with MNI152 coordinates

### ISSUE THREAD

**Issue by marinaferalv** [Washington-University/HCPpipelines#243]
Dear experts,

I don't have experience using workbech and I have some basic questions. I would like to start using it to create a surface binary mask with circular rois around the vertex corresponding to certain MN152 coordinates.

I have seen that maybe I can use the function wb_command -surface-coordinates-to-metric to find the correspondence between the MNI152 coordinates and the vertex IDs. Which surface should I use as input with this function? Is there any MNI152 surface in the workbech dependencies?

On the other hand, I have seen that I could use the wb_command -surface-geodesic-rois function to draw ROIs around the vertices and that the output of this function is a "metric file". How can I convert this file to a Freesurfer surface (fsaverage6) binary mask?

Thank you in advance.

Best regards,
Marina

**Comment by glasserm** [comment]
As I said in your Connectome Workbench ticket, this is best addressed on the hcp-users <hcp-users@humanconnectome.org> mailing list.

**Comment by marinaferalv** [comment]
Sorry, it was a misunderstanding. Thank you for sending me the correct way to proceed
