### ISSUE TITLE
FSL imrm issues

### ISSUE THREAD

**Issue by dicemt** [Washington-University/HCPpipelines#246]
In FSL 6.0.6.{0,1,2} (and perhaps 6.0.5?), imrm does not work as intended, getting errors in Diffusion preprocessing.
(a matter of pattern matching character/wildcard '?') 
https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2302&L=FSL&O=D&P=118535

Modifying
imrm ${basename}_b0_???? -> imrm ${basename}_b0_????.nii*
has worked fine.

https://github.com/Washington-University/HCPpipelines/blob/1334b35ab863540044333bbdec70a68fb19ab611/DiffusionPreprocessing/scripts/basic_preproc_norm_intensity.sh#L57
https://github.com/Washington-University/HCPpipelines/blob/098a9c5117fece112e46281b0a7cebb8875be7c2/DiffusionPreprocessing/scripts/basic_preproc_sequence.sh#L143-L144

**Comment by glasserm** [comment]
This is a known bug.  Jure has some ideas on how to fix.

**Comment by demsarjure** [comment]
Yes, it seems like FSL changed the behavior of `imrm` going from 6.0.5 to 6.0.6. I would say that the new behavior is the correct one, but need to run this by FSL folks before coding this simple change. I plan to do this later this week.

For example, if we have two images `Pos_b0_1234.nii.gz` and `Pos_b0_4321.nii.gz` previously the command 

``` bash
imrm Pos_b0_????
```

Would delete both of them, so in a way the question marks would also encapsulate .nii.gz. Like mentioned, now this only works if the above command is changed to

```
```

**Comment by mharms** [comment]
Per the jiscmail link above, this is apparently due to a bug introduced into FSL.  The whole point of the `imrm` and `imcp` commands is that you aren't supposed to need to supply the image extension.  That said, sounds like we may need to modify our pipeline code to accommodate this FSL bug.

**Comment by glasserm** [comment]
Sounds good.

**Comment by demsarjure** [comment]
Agreed.

**Comment by dicemt** [comment]
In case of reverting, I would suggest describing "not to use FSL 6.0.5-6.0.6.*" in the wiki. (now, the wiki recommends FSL 6.0.5)
https://github.com/Washington-University/HCPpipelines/wiki/Installation-and-Usage-Instructions

Alternatively, keeping "imrm ${basename}b0????.nii*" would also be fine without modifying the wiki.

**Comment by demsarjure** [comment]
Pull request is available at https://github.com/Washington-University/HCPpipelines/pull/248.

**Comment by mharms** [comment]
Thinking about this more broadly, why is only an issue in the DiffusionPreprocessing scripts?  Shouldn't it be an issue anywhere that `imrm` is used?

**Comment by coalsont** [comment]
I would guess that most uses of imrm don't use wildcard characters.  Since the file extension is missing on the original line, the shell can't do the globbing, and therefore imrm itself has to do the globbing.

**Comment by dicemt** [comment]
I searched imrm within the repository and found four lines using '?' with imrm.
https://github.com/Washington-University/HCPpipelines/search?q=imrm

The one line I did not mention was in eddy_postproc.sh, but the failure to delete them appeared not to affect the pipeline to complete (at least in its current form).
But, I guess modifying eddy_postproc.sh would be fine just in case (or for the future possibility).
https://github.com/Washington-University/HCPpipelines/blob/5719c91af6698445b0cc632830e37aef044a4c32/DiffusionPreprocessing/scripts/eddy_postproc.sh#L164

**Comment by demsarjure** [comment]
I ran my own tests and it seems like `imrm` works fine if it has no `?` signs in it. It works fine with other wildcard symbols, e.g., the asterisk (`*`).

Like @dicemt mentioned, there are four locations where `imrm` is used in combination with `?`. We resolved three of them, the fourth one is mentioned in the previous post:

```
${FSLDIR}/bin/imrm ${datadir}/grad_dev_?
```

The above line of code is supposed to delete three files `grad_dev_x`, `grad_dev_y` and `grad_dev_z`. I propose that we unwrap the line into three separate calls:

```
	# Delete each of the grad_dev files individualy due to bug in behavior of imrm introduced in FSL 6.0.6
	${FSLDIR}/bin/imrm ${datadir}/grad_dev_?
	${FSLDIR}/bin/imrm ${datadir}/grad_dev_?
	${FSLDIR}/bin/imrm ${datadir}/grad_dev_?
```

**Comment by coalsont** [comment]
I would expect you be able to do that in one line:
`imrm "${datadir}/grad_dev_x" "${datadir}/grad_dev_y" "${datadir}/grad_dev_z"`
We could also use the same `.nii*` trick, unless we are worried about a file named like `grad_dev_1.nii.gz` also existing there...

**Comment by coalsont** [comment]
As for your tests, I suspect why `*` works is because you always put it on the end of the filename (which means the shell can do the globbing because it can include the file extension), so for instance `imrm test_*_file` would fail to remove `test_junk_file.nii.gz`.

**Comment by dicemt** [comment]
Or it can be much shorter if you want:
`imrm "${datadir}/grad_dev_{x,y,z}"`

**Comment by coalsont** [comment]
That brace expansion appears to need to be unquoted to work properly: `imrm "${datadir}"/grad_dev_{x,y,z}`, similar to glob characters.  I don't think many people have seen brace expansion before, but `?` is also a much rarer glob character than `*`, so...
