### ISSUE TITLE
PreFreeSurfer Batch script error

### ISSUE THREAD

**Issue by fuguemahlyfe** [Washington-University/HCPpipelines#262]
I am trying to run '/Pipelines/Examples/Scripts/PreFreeSurferPipelineBatch.sh' but the following error happens:
Error submitting job - Command not usable: Cannot find script/binary '/PreFreeSurfer/PreFreeSurferPipeline.sh'

How to solve this problem?

Thank you very much for your time.

**Comment by glasserm** [comment]
Did you set up ${HCPpipelines}/Examples/Scripts/SetUpHCPPipeline.sh appropriately for your setup?

**Comment by fuguemahlyfe** [comment]
Thank you for your reply. '/PreFreeSurfer/PreFreeSurferPipeline.sh' can be found now.
I am now trying to run 'PreFreeSurferPipelineBatch.sh', but I don't have T2w data.
I specified legacyStyleData="LegacyStyleData" in 'PreFreeSurferPipelineBatch.sh' before queueing command.
After the queueing command line, I also typed --processing-mode="$legacyStyleData" in 'PreFreeSurferPipelineBatch.sh'

However, I am still getting the following error"
Error submitting job - ERROR: Could not find image /unprocessed/3T/T2w_SPC?/102_3T_T2w_SPC?.nii.gz

How can I solve this problem? Thank you very much.

**Comment by glasserm** [comment]
You need to unset the argument in the launcher script that sets a T2w input.

**Comment by fuguemahlyfe** [comment]
Thank you for your help.
Sorry for bombarding you with questions (I am new to this).
The prefreesurfer script stops at  BiasFieldCorrection_T1wOnly.sh (line 114) because it cannot locate T1_acpc_dc. The acpc_dc, acpc_dc_brain files are not generated after running T2wToT1wDistortionCorrectAndReg.sh

How can I solve this problem? Thank you for your time.

**Comment by glasserm** [comment]
How did you call the pipeline?

**Comment by fuguemahlyfe** [comment]
I first typed these the following in the command:
module load fsl-6.0.5
module load freesurfer-7.2.0 
export SUBJECTS_DIR=/ubsn/home/hlnwong/NEOM/103 
export FSLDIR=/ubsn/apps/fsl/fsl-6.0.5
export PATH=/ubsn/apps/fsl/fsl-6.0.5/bin:$PATH
export PATH=$PATH:/ubsn/home/hlnwong/software/HCP/gradunwarp-1.2.1/gradunwarp-1.2.1/gradunwarp/core/gradient_unwarp.py
. $FSLDIR/etc/fslconf/fsl.sh
export FREESURFER_HOME=/ubsn/apps/freesurfer/freesurfer-7.2.0
source $FREESURFER_HOME/SetUpFreeSurfer.sh

Then I typed srun ./PreFreeSurferPipelineBatch.sh & in the command
I have attached some screenshots for your reference. Thank you very much.
![capture1](https://user-images.githubusercontent.com/56466459/234162830-c081314d-df17-453b-b26e-cd3b29f35ad5.PNG)
![Capture2](https://user-images.githubusercontent.com/56466459/234162835-cdead21b-3a5f-4897-b5ce-0dff31913224.PNG)

**Comment by glasserm** [comment]
I don't think any of the above is needed if you have properly edited the HCP Pipelines setup script (https://github.com/Washington-University/HCPpipelines/blob/master/Examples/Scripts/SetUpHCPPipeline.sh).  You will then need to edit the [PreFreeSurferPipelineBatch](https://github.com/Washington-University/HCPpipelines/blob/master/Examples/Scripts/PreFreeSurferPipelineBatch.sh) script to be appropriate for your edits.  I need to know the commandline executed at the end of the script.

**Comment by fuguemahlyfe** [comment]
I have made the edits and the scripts are running now.
Thank you very much for your help!
