### ISSUE TITLE
eddy_openmp is deprecated in FSL 6.0.6

### ISSUE THREAD

**Issue by dicemt** [Washington-University/HCPpipelines#264]
### Another FSL 6.0.6 issue 
**eddy_openmp** is deprecated in FSL 6.0.6 and the successor is **eddy_cpu**
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/WhatsNew?action=AttachFile&do=get&target=6.0.6.md

So, we need to modify **run_eddy.sh** to use eddy_cpu if eddy_openmp is not found, perhaps within the local **determine_eddy_tools_for_supported_six_series** function.
https://github.com/Washington-University/HCPpipelines/blob/e81697b73bf19296b4d0fd95b141b2d78a1514d0/DiffusionPreprocessing/scripts/run_eddy.sh#L301
```
if [ ! -f ${g_stdEddy} ]; then
    # eddy_openmp is deprecated in FSL 6.0.6
    g_stdEddy="${FSLDIR}/bin/eddy_cpu"
fi
```

Alternatively, we can explicitly tell bash to use an appropriate eddy executable (depending on the FSL version) under conditional statements within the local **determine_eddy_tools_to_use** function.
https://github.com/Washington-University/HCPpipelines/blob/e81697b73bf19296b4d0fd95b141b2d78a1514d0/DiffusionPreprocessing/scripts/run_eddy.sh#L447-L468
```
 		elif [[ $((${fsl_tertiary_version})) -ge 6 ]]; then 
 			# 6.0.6+
				g_stdEddy="${FSLDIR}/bin/eddy_cpu"
				g_gpuEnabledEddy="${FSLDIR}/bin/eddy_cuda"
```	

But the latter option may be somewhat redundant and will require rewriting the code in the near future (FSL 6.1.0+).

**Comment by coalsont** [comment]
Should be fixed in 9d00ac5f2e5ca40a707b8eac7a2a5450b195a351
