### ISSUE TITLE
Some key value conflicting warning about the postfreesurfer

### ISSUE THREAD

**Issue by jaja123j** [Washington-University/HCPpipelines#277]
reading colortable from annotation file...
colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)
reading colortable from annotation file...
colortable with 76 entries read (originally Simple_surface_labels2008.txt)
WARNING: input sphere is either unusually irregular or not centered, inspect the input
reading colortable from annotation file...
colortable with 36 entries read (originally /autofs/space/tanha_002/users/greve/fsdev.build/average/colortable_desikan_killiany.txt)
reading colortable from annotation file...
colortable with 76 entries read (originally Simple_surface_labels2008.txt)
WARNING: input sphere is either unusually irregular or not centered, inspect the input
WARNING: conflicting key value for label 'R_bankssts' reassigned to key 36
WARNING: conflicting key value for label 'R_caudalanteriorcingulate' reassigned to key 37
WARNING: conflicting key value for label 'R_caudalmiddlefrontal' reassigned to key 38
WARNING: conflicting key value for label 'R_corpuscallosum' reassigned to key 39
WARNING: conflicting key value for label 'R_cuneus' reassigned to key 40
WARNING: conflicting key value for label 'R_entorhinal' reassigned to key 41
WARNING: conflicting key value for label 'R_fusiform' reassigned to key 42
WARNING: conflicting key value for label 'R_inferiorparietal' reassigned to key 43

there are so many warnings like the Previous example.it seems that the segmentation label has some problem,maybe it will has an influence on the Diffusion preprocess

**Comment by jaja123j** [comment]
is it serious?the code can be runed successfully but I think it will take some problem.

**Comment by jaja123j** [comment]
is it serious?the code can be runed successfully but I think it will take some problems.

**Comment by glasserm** [comment]
Not serious.

**Comment by jaja123j** [comment]
> Not serious.
thanks,I will ignore these warnings!
