### ISSUE TITLE
GE HeathCare B0 Fieldmaps processing

### ISSUE THREAD

**Issue by brice82** [Washington-University/HCPpipelines#283]
Dear HCPpipelines developers,  

The processing of the GE HealthCare fieldmaps seems incomplete. 
I am only speaking about the "official" 2D and 3D B0 Fieldmaps provided by the manufacturer. 

The below script `FieldMapPreprocessingAll.sh` does not apply the unwrapping, and just convert the fieldmap in rad/s. 
https://github.com/Washington-University/HCPpipelines/blob/5df95e40378a71457fd510ae8e465db2fee6f48d/global/scripts/FieldMapPreprocessingAll.sh#L148 

These fieldmaps comes out of the scanner as 2 volumes, first the Fieldmap in Hertz (not degrees) and second the magnitude image (of the shortest echo). The fieldmaps are not unwrapped by the scanner software. 

Old dcm2niix (before v1.0.20210410) use to convert the GEHC B0Maps as a 2 volumes NIFTI file (Volume 1 is the B0Map in Hertz, and Volume 2 the magnitude image). Starting at dcm2niix v1.0.20210410 the B0Maps are split as 2 files (the magnitude and the b0map_fieldmaphz in Hertz - with the suffix "_fieldmaphz" for easy identification). Then dcm2niix v1.0.20220720 adds the TE1 and TE2 in the json file (to compute `DeltaTE` easily).

Additionally,  FSL version 6.0.7.1 and later can handle directly the GE Fieldmaps via the script `fsl_prepare_fieldmap`. Usage is simply:
```
fsl_prepare_fieldmap GEHC_FIELDMAPHZ 3dB0map_fieldmaphz mag_3dB0map fmap_rads DeltaTE
```
The current script `FieldMapPreprocessingAll.sh` seems to only consider the case of old dcm2niix (the 2 volumes NIfTI file case). 

For **backward compatibility**, we could fix the existing `GeneralElectricFieldMap` pipeline (to include the unwrapping / `fsl_prepare_fieldmap` processing) and continue to consider a 2 volumes NIFTI file. Then we should add `DeltaTE` as a mandatory  augument for this pipeline (and eventually use a known trick to estimate the DeltaTE – or maybe propose a separate script that would do that). This might help to use the HCPpipelines on existing and already converted data. 

For **forward compatibility**, we could make a new pipeline `GEHealthCareFieldMap` pipeline with mandatory inputs `DeltaTE` and the 2 separates files for fieldmap and magnitude as provided by recent dcm2niix.

If this is an acceptable plan for you, I would be happy to provide a fix for the following files:
```
HCPpipelines/global/scripts/FieldMapPreprocessingAll.sh
HCPpipelines/Examples/Scripts/GenericfMRIVolumeProcessingPipelineBatch.sh
HCPpipelines/Examples/Scripts/Historical/7T/GenericfMRIVolumeProcessingPipelineBatch.7T.sh
HCPpipelines/Examples/Scripts/PreFreeSurferPipelineBatch.sh
HCPpipelines/PreFreeSurfer/PreFreeSurferPipeline.sh
HCPpipelines/PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh
HCPpipelines/fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh
HCPpipelines/fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh
```
Let me know. 
Thanks

**Comment by mharms** [comment]
Some questions:

1. Is there any version of GE in which the output would be something other an Hz map and magnitude image?  e.g., phase and magnitude; both echoes as magnitude images; real and imaginary; etc ?
2. What changed in `fsl_prepare_fieldmap` such that one specifically needs `6.0.7.1` or later?  Did it merely add GEHC_FIELDMAPHZ as an allowable "scanner", and then convert Hz to rad/s internally in that case?  Because if that is all it is doing, could we instead consider just converting Hz to rad/s in the pipeline itself, maybe with a scaling applied (to reflect the 0-4096 range used by Siemens), and then submit it as a "SIEMENS" scanner, and thereby avoid needing to make it dependent on a recent FSL version?
3. Related, other than the Hz vs. rad/s difference, is there any difference in the steps that need to be applied between Siemens and GE?

**Comment by brice82** [comment]
Here are the answers:
1. The official B0 Maps sequence from GEHC have always been in Hertz and magnitude. 
A number of site have used custom homemade pulse sequence outputing both echoes real and imaginary or phase/magnitude, but this is very old. Probably, before 2012. This is out of scope. 

2. The changes in `fsl_prepare_fieldmap` are not big, this is mainly the range check, and the conversion to phase (radian) which differs. It is possible to format in siemens phase format [-2048 2048] for FSL version before `6.0.7.1`. No difficulty here. 

3. No, beside the Hertz vs phase difference then all processing is essentially the same.

**Comment by mharms** [comment]
Given that, I'm curious what others (@glasserm, @coalsont) think as to whether we should introduce an FSL version dependency for running `fsl_prepare_fieldmap` on the "native" Hz map provided by GE, or instead modify the Hz map to be equivalent to a Siemens rad/s map and then just send the resulting inputs through the existing Siemens code.

**Comment by glasserm** [comment]
Could we put a conditional in that checks the FSL version and operates accordingly?

**Comment by mharms** [comment]
We could, but it would unnecessary to do that if we simply adjust the Hz map (per above) to work with all FSL versions as a Siemens-style rad/s map instead.

**Comment by glasserm** [comment]
I am trying to be sensitive to the fact that GE may wish for the pipelines to be explicit about full GE support rather than just converting and using Siemens modes.  Given that a GE employee is implementing this for us, such sensitivity is a good idea.

**Comment by mharms** [comment]
From the user's perspective, they would use a "GE mode".  I'm trying to map out how we want to implement the details that would be transparent to the user.

**Comment by glasserm** [comment]
Sure, but perhaps GE would prefer the solution I proposed, so we should not argue against that. If they don't care, I don't care either.

**Comment by mharms** [comment]
I guess my inclination is that, for backwards compatibility, we continue to allow the two volume input with the `GeneralElectricFieldMap` option (although perhaps create a more informative name for it), but fix it so that it does the unwrapping (which I believe is the only thing wrong with it, per above?), which I believe we will conveniently accomplish just by using `fsl_prepare_fieldmap` from FSL version `6.0.7.1` or later?

So, just to be very clear, the proposal is that *both* approaches will error out after we make these changes unless the FSL version is >= `6.0.7.1`, since we will need that version of `fsl_prepare_fieldmap` for both approaches?

**Comment by brice82** [comment]
Thanks for your inputs. You seem to be more in favor of the proposition 1 then. 

Yes, in the end the only missing part in the unwrapping and clean-up from `fsl_prepare_fieldmap`. 
There is also some misleading comments to fix like here 
https://github.com/Washington-University/HCPpipelines/blob/5df95e40378a71457fd510ae8e465db2fee6f48d/global/scripts/FieldMapPreprocessingAll.sh#L152 
This gives the impression that the fieldmaps are in degrees, and then they are multiplied by `2*pi`and this ends-up being a suitable fieldmap in rad/s (of course, this is Hertz, and once multiplied by `2*pi`it is effectively in rad/s). 

No no, in every case, the proposal is to use:
-  `fsl_prepare_fieldmap GEHC_FIELDMAPHZ .....` if FSL version `>= 6.0.7.1` is available
- otherwise convert the Fieldmap in Siemens format and use `fsl_prepare_fieldmap SIEMENS .....` for FSL `< 6.0.7.1` (maybe adding a warning in this case).
 
So, this will use the best available option and avoid too much dependence on FSL version . 

All clear ?

**Comment by mharms** [comment]
This is good.  We are finally getting to the precise thing I was trying to clarify above. You (understandably) want to make use of `fsl_prepare_fieldmap` if the FSL version is appropriate, but if not, there would be a backup hack in which we turn the GE Hz map into a Siemens-style rad/s map. While convenient for users, that to me seems a potential source for bugs (and harder to maintain).  Which is why I'm wondering if we shouldn't just drop support for GE dual-echo fieldmap correction if the FSL version installed is < `6.0.7.1`.

I think we need @coalsont to chime in, as to whether he has a preference.

**Comment by brice82** [comment]
oh, yes, this is also a possibility and probably easier. No fieldmap processing for GE if FSL `< 6.0.7.1`.

**Comment by coalsont** [comment]
I suppose telling the user they need to upgrade FSL if they want to use a new feature is acceptable.  If someone is worried about processing consistency with prior data enough to freeze the FSL version, they probably aren't collecting a different fieldmap type than they used to, either.

**Comment by glasserm** [comment]
I am okay with this if Brice/GE is okay with it.

**Comment by coalsont** [comment]
The initial proposal says that the existing GE option would change its behavior and would require an additional argument.  Do we think that nobody was actually using this mode?  If someone was using it on data where it worked, it would be a little friendlier to users to keep the old version around, for instance with a "legacy" name if we want to repurpose the existing name.

**Comment by mharms** [comment]
The "old/existing" version was not implemented correctly.  We can preserve the mode (`dcmethod`) which really relates to how the data is packaged (one volume with two frames).  But there is no reason to preserve code which isn't implementing something correctly.

**Comment by coalsont** [comment]
If nobody expects that the old code needs data that is already unwrapped (to the extent that it is necessary), then yes, it sounds like removing/replacing the old code is fine.

**Comment by brice82** [comment]
Dear All, 

While correcting `PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh'

I saw something that might be incorrect in the help of input `--fmapphase` here
https://github.com/Washington-University/HCPpipelines/blob/5df95e40378a71457fd510ae8e465db2fee6f48d/PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh#L84

Why would this input be a "single 4D image containing 2x3D volumes" ? 
It looks like a single volume of phase difference for both Siemens and Phillips (and in Hertz for GE).

**Comment by glasserm** [comment]
Yes, that is wrong, so you can fix it in your PR.

**Comment by brice82** [comment]
Yes. I fix it while I am modifying this exact same line. Thanks.

**Comment by brice82** [comment]
Dear All, 
I have modified `./global/scripts/FieldMapPreprocessingAll.sh` and I have reported the corresponding changes in the several sections: 
1- the PreFreeSurferPipeline
`./Examples/Scripts/PreFreeSurferPipelineBatch.sh`
`./PreFreeSurfer/PreFreeSurferPipeline.sh`
`./PreFreeSurfer/scripts/T2wToT1wDistortionCorrectAndReg.sh` 
2 - the fMRI Volume processing
`./Examples/Scripts/GenericfMRIVolumeProcessingPipelineBatch.sh`
`./Examples/Scripts/Historical/7T/GenericfMRIVolumeProcessingPipelineBatch.7T.sh`
`./fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh`
`./fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh`

I have been find-grep-ing all over the code, I can't find other places that requires modification. 
Do you have any other file/pipeline in mind that requires FieldMaps and that could be impacted by the modification of `FieldMapPreprocessingAll.sh`? 

Do you keep tests scripts somewhere ? is there any normalized way of documenting the test ?
(if not I will push the tests scripts in a separate repo just in case)

Thanks and let me know.

**Comment by glasserm** [comment]
I don't think we currently support fieldmaps for diffusion, so this looks like the scripts to modify.  I don't have any GE data for testing, does anyone else? @mharms @demsarjure.

**Comment by brice82** [comment]
I have data to test (7 subjects - I guess this is enough). 
Right now, the test for fMRI volume processing is running. Other PreFreeSurferPipeline and FieldMapProcessingAll.sh already tested.

**Comment by brice82** [comment]
I think I know. I will ping you in private to double check.

**Comment by brice82** [comment]
Dear All, 

The pull-request is here. 
https://github.com/Washington-University/HCPpipelines/pull/285 

If you and need more details about the tests I have made, just let me know.
I have screenshots, output-logs, test scripts, data etc...

**Comment by brice82** [comment]
Closing this issue. 
Ths GEHC B0 FieldMap processing is fix by via PR https://github.com/Washington-University/HCPpipelines/pull/285 and merged at commit https://github.com/Washington-University/HCPpipelines/commit/ebf1addd745b5a17d7597fe5b73fe49cc188651f .
