### ISSUE TITLE
Yash Please Restore These Lines to their Original Paths

### ISSUE THREAD

**Issue by glasserm** [Washington-University/HCPpipelines#286]
https://github.com/Washington-University/HCPpipelines/blob/840623f9fc205c84bde46a89db616badeb935680/Examples/Scripts/FreeSurferPipelineBatch.sh#L42-L44

**Comment by coalsont** [comment]
May be helpful:

https://github.com/Washington-University/HCPpipelines/blob/767ae8e0d635ad23bd16f6455eeb4c12e51b75b8/Examples/Scripts/FreeSurferPipelineBatch.sh#L42-L44

**Comment by ythackerCS** [comment]
Resolved, however Tim needs to check why I was not able to push. I ended up editing live on github to commit the change.
