### ISSUE TITLE
mris_apply_reg error: Option --lta unknown

### ISSUE THREAD

**Issue by cdlyr** [Washington-University/HCPpipelines#287]
Hi,

I was trying to follow the instruction to run the "FreeSurferPipelineBatch.sh" on the Pipelines_ExampleData. However, in log file the error message popped up during "Creating lh.white.preaparc.rawavg" for "mris_apply_reg --lta" as "ERROR: Option --lta unknown". I took a look at the mris_apply_reg function and  the flag is added in freesurfer7 instead of version6.0. Do I need to configure the pipeline with freesurfer v7.4? My current freesurfer version is "freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c" and the system is Red Hat Enterprise Linux release 8.9.

Thanks,
Yiran

**Comment by coalsont** [comment]
All our customizations of freesurfer are here:

https://github.com/Washington-University/HCPpipelines/tree/master/FreeSurfer/custom

I don't see `--lta` passed to that executable from our custom versions.  I suggest that you double check your environment to make sure that it doesn't have anything related to freesurfer 7 on `$PATH` (or any custom things in `$HOME/bin`, etc).  In particular, echoing `$PATH` in the Batch launcher script somewhere after it sources your SetUp file may give some hint as to what is going on.

We have not yet implemented freesurfer 7 support, as we have not managed to get surfaces of similar quality to those from freesurfer 6 on our data.

**Comment by glasserm** [comment]
FS 7.X is not currently supported in the HCP Pipelines as Tim notes.  We have been trying to work with the FreeSurfer folks to get its surface accuracy performance to match prior versions but have not yet been successful.  Thus, we don't recommend using it at this time for HCP-Style analyses.

**Comment by cdlyr** [comment]
Thanks for your reply. Actually I am using freesurfer 6.0 in the pipeline. My freesurfer version is freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c via "recon-all -version". I attached the recon-all.log file here. Can you check if anything is wrong?

[recon-all.log](https://github.com/Washington-University/HCPpipelines/files/14609530/recon-all.log)

**Comment by coalsont** [comment]
This looks suspicious, though I'm not sure how freesurfer handles version numbering of individual tools:

```
/autofs/projects-t3/DRNM/workshop/packages/freesurfer/bin/conf2hires --threads 1 --T2 --s 100307 --trilin

freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0-2beb96c
conf2hires 7.1.1
```

I also would have expected it to be using our custom version of conf2hires, not the one in freesurfer...did you manually put `$HCPPIPEDIR/FreeSurfer/custom` on your `$PATH`, but in a position that is after `/autofs/projects-t3/DRNM/workshop/packages/freesurfer/bin/`?  We probably shouldn't be outputting a message about whether we are adding something to `$PATH`, and just always do it silently, to prevent this possibility...

**Comment by cdlyr** [comment]
Thanks for catching the mistake. I did add $HCPPIPEDIR/FreeSurfer/custom to $PATH after the original one so it used the wrong file. But v6 shouldn't have the "conf2hires" function inside. Somehow my freesurfer v6 had some functions existing in v7. I reinstalled freesurfer v6 and those files disappeared and I can smoothly run the examples.
