### ISSUE TITLE
Error running the GenericfMRIVolumeProcessingPipeline.sh script

### ISSUE THREAD

**Issue by jayashree15** [Washington-University/HCPpipelines#288]
Hi, I ran the GenericfMRIVolumeProcessingPipeline.sh script and the script seem to error out at the ComputeSpinEchoBiasField.sh for one of the volumes (please refer attached log file at line 561) and not the other. I provided the same echo field maps for both of these volumes and I'm unsure why I get this error. Please let me know if you have any insights.

Thanks,
Jayashree

[GenericfMRIVolumeProcessingPipeline.sh.o55026.txt](https://github.com/Washington-University/HCPpipelines/files/14796170/GenericfMRIVolumeProcessingPipeline.sh.o55026.txt)
[GenericfMRIVolumeProcessingPipeline.sh.o63328.txt](https://github.com/Washington-University/HCPpipelines/files/14796172/GenericfMRIVolumeProcessingPipeline.sh.o63328.txt)

**Comment by glasserm** [comment]
Both files have some highly suspect stats coming out of ComputeSpinEchoBiasField.  I wonder if your SE field maps and SBRef images are not matched?

**Comment by jayashree15** [comment]
Issue is resolved
