### ISSUE TITLE
Question for cortical surface atlas label

### ISSUE THREAD

**Issue by Git-zry** [Washington-University/HCPpipelines#296]
I have used the fsaverage.L_LR.spherical_std.164k_fs_LR.surf.gii and MSMSulc.refsulc.164k_fs_LR.dscalar.nii files from the global/templates/standard_mesh_atlases directory for cortical surface registration. Now I need to calculate the Dice coefficient before and after registration. Could you please let me know where I can find the label files for this atlas?

Looking forward to your prompt response.

**Comment by glasserm** [comment]
This sounds like a question of how to do an analysis rather than a question about the HCP Pipelines code.  I would ask that on the hcp-users mailing list.
