### ISSUE TITLE
An error about IcaFix

### ISSUE THREAD

**Issue by ContestantsD** [Washington-University/HCPpipelines#308]
Thu Oct 10 19:42:49 CST 2024:hcp_fix: Check rest_AP_hp2000.ica/.fix.log for log output from cleanup stage
FIX Feature extraction for Melodic output directory: rest_AP_hp2000.ica
 create edge masks
 run FAST
 registration of standard space masks
 extract features
FIX Classifying components in Melodic directory: rest_AP_hp2000.ica using training file: /usr/local/fsl_fix/fix/training_files/HCP_hp2000.RData and threshold 10
FIX features not already generated, so creating them now.
FIX Feature extraction for Melodic output directory: rest_AP_hp2000.ica
 create edge masks
 run FAST
 registration of standard space masks
 extract features
No valid labelling file specified
Thu Oct 10 20:08:11 CST 2024:hcp_fix: Done running FIX
Could not find a supported file with prefix "rest_AP_hp2000.ica/filtered_func_data_clean"
Thu Oct 10 20:08:11 CST 2024:hcp_fix: While running '/media/disk10t_1/qrd/HCPpipelines-master/ICAFIX/hcp_fix /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP 2000 FALSE HCP_hp2000.RData 10 FALSE':
Thu Oct 10 20:08:11 CST 2024:hcp_fix: ERROR: '/home/qrd/fsl/bin/immv' command failed with return code: 1

**Comment by ContestantsD** [comment]
I have checked the Integrity of immv, HCP_hp2000.RData and MCR, I can not identify the cause of the issue. Please help me!

**Comment by glasserm** [comment]
There are other logfiles for matlab and R.  Have a look in those for the actual error causing "No valid labelling file specified."

**Comment by ContestantsD** [comment]
> There are other logfiles for matlab and R. Have a look in those for the actual error causing "No valid labelling file specified."

Hello, I'm using mode0. Where should I find the error_log?

**Comment by glasserm** [comment]
${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt
${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log
${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log

**Comment by ContestantsD** [comment]
> ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log

qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
------------------------------------------
Setting up environment variables
---
LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64

hp =

        2000


TR =

    0.8000

**Comment by RuiWang0805** [comment]
> > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> 
> ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> ## Setting up environment variables
> LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> 
> hp =
> 
> ```
>     2000
> ```
> 
> TR =
> 
> ```
> 0.8000
> ```
你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人

**Comment by ContestantsD** [comment]
> > > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> > 
> > 
> > ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> > ## Setting up environment variables
> > LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> > hp =
> > ```
> >     2000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > TR =
> > ```
> > 0.8000
> > ```
> 
> @ContestantsD 你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人

你好，我看了你在这个项目下留的questions，感觉你并没有利用好别人提出来的问题及其解决方案、官方给出的指导以及其他资源，所以不是很想与你邮箱交流。最明显的，官方为ICAFIX脚本写的ReadMe里明确指出要用MCR-V93，V93对应的Matlab版本是2017b，你却用2016a，还问为什么这样不行，我觉得这样很无厘头

**Comment by RuiWang0805** [comment]
> > > > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> > > 
> > > 
> > > ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> > > ## Setting up environment variables
> > > LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> > > hp =
> > > ```
> > >     2000
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > TR =
> > > ```
> > > 0.8000
> > > ```
> > 
> > 
> > @ContestantsD 你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人
> 
> 你好，我看了你在这个项目下留的questions，感觉你并没有利用好别人提出来的问题及其解决方案、官方给出的指导以及其他资源，所以不是很想与你邮箱交流。最明显的，官方为ICAFIX脚本写的ReadMe里明确指出要用MCR-V93，V93对应的Matlab版本是2017b，你却用2016a，还问为什么这样不行，我觉得这样很无厘头

不好意思，我刚刚接触这个，现在重新按照他的guidence重新跑的，谢谢

**Comment by ContestantsD** [comment]
> > > > > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> > > > 
> > > > 
> > > > ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> > > > ## Setting up environment variables
> > > > LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> > > > hp =
> > > > ```
> > > >     2000
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > TR =
> > > > ```
> > > > 0.8000
> > > > ```
> > > 
> > > 
> > > @ContestantsD 你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人
> > 
> > 
> > 你好，我看了你在这个项目下留的questions，感觉你并没有利用好别人提出来的问题及其解决方案、官方给出的指导以及其他资源，所以不是很想与你邮箱交流。最明显的，官方为ICAFIX脚本写的ReadMe里明确指出要用MCR-V93，V93对应的Matlab版本是2017b，你却用2016a，还问为什么这样不行，我觉得这样很无厘头
> 
> 不好意思，我刚刚接触这个，现在重新按照他的guidence重新跑的，谢谢

谁不是刚接触这个呢？

**Comment by RuiWang0805** [comment]
> > > > > > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> > > > > 
> > > > > 
> > > > > ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> > > > > ## Setting up environment variables
> > > > > LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> > > > > hp =
> > > > > ```
> > > > >     2000
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > TR =
> > > > > ```
> > > > > 0.8000
> > > > > ```
> > > > 
> > > > 
> > > > @ContestantsD 你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人
> > > 
> > > 
> > > 你好，我看了你在这个项目下留的questions，感觉你并没有利用好别人提出来的问题及其解决方案、官方给出的指导以及其他资源，所以不是很想与你邮箱交流。最明显的，官方为ICAFIX脚本写的ReadMe里明确指出要用MCR-V93，V93对应的Matlab版本是2017b，你却用2016a，还问为什么这样不行，我觉得这样很无厘头
> > 
> > 
> > 不好意思，我刚刚接触这个，现在重新按照他的guidence重新跑的，谢谢
> 
> 谁不是刚接触这个呢？

OK，打扰了，祝你顺利

**Comment by RuiWang0805** [comment]
> > > > ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/fix/logMatlab.txt ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix.log ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName}/${fMRIName}_hp${HP}.ica/.fix_2b_predict.log
> > > 
> > > 
> > > ## qrd@P21:~$ cat /media/disk10t_1/qrd/data/ABCD/examples/sub-NDARINV003RTV85_ses-baselineYear1Arm1/MNINonLinear/Results/rest_AP/rest_AP_hp2000.ica/.fix.log
> > > ## Setting up environment variables
> > > LD_LIBRARY_PATH is .:/usr/local/MATLAB/MATLAB_Runtime//v93/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime//v93/sys/opengl/lib/glnxa64
> > > hp =
> > > ```
> > >     2000
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > TR =
> > > ```
> > > 0.8000
> > > ```
> > 
> > 
> > @ContestantsD 你好，我也遇到相同的情况，能不能邮箱交流一下，我也是中国人
> 
> 你好，我看了你在这个项目下留的questions，感觉你并没有利用好别人提出来的问题及其解决方案、官方给出的指导以及其他资源，所以不是很想与你邮箱交流。最明显的，官方为ICAFIX脚本写的ReadMe里明确指出要用MCR-V93，V93对应的Matlab版本是2017b，你却用2016a，还问为什么这样不行，我觉得这样很无厘头

您好，可以请教一个问题吗，我的报错是hcp_fix: ERROR: hp = 0 not currently supported，我将hp值改成0和2000是可以跑到，不知道这是啥原因，期待您的回复，麻烦了。
