### ISSUE TITLE
Bug in the FieldMapPreprocessingAll.sh

### ISSUE THREAD

**Issue by younghoo** [Washington-University/HCPpipelines#318]
Hi, 

I found a bug in the [FieldMapPreprocessingAll.sh](https://github.com/Washington-University/HCPpipelines/blob/master/global/scripts/FieldMapPreprocessingAll.sh) of HCPpipelines v5.0.0. In line 170, one blank space was missing in the if conditional statement: `if [[ "$input" == *@*]]`, which would cause failure when running in the official example dataset.

**Comment by coalsont** [comment]
Thanks for reporting, I have pushed a change that should fix it.  Try master and see if it works.
