### ISSUE TITLE
GenericfMRIVolumeProcessingPipelineBatch.7T.sh

### ISSUE THREAD

**Issue by tetsuyacht** [Washington-University/HCPpipelines#43]
The script does not work. The variable $BiasCorrection is not assigned and the argument --biascorrection is missing.

**Comment by glasserm** [comment]
Can you post your pipeline call?

**Comment by tetsuyacht** [comment]
I attach the PDF of the batch script I'm using.
I added `BiasCorrection="SEBASED"` and `--biascorrection=$BiasCorrection` in lines 177 and 240.

[GenericfMRIVolumeProcessingPipelineBatch.7T.sh.pdf](https://github.com/Washington-University/Pipelines/files/1093299/GenericfMRIVolumeProcessingPipelineBatch.7T.sh.pdf)

**Comment by kjamison** [comment]
I may be misunderstanding...

Are you suggesting that we add the BiasCorrection flag to the example
script (probably a good idea), or saying your script doesn't work after
your modification?

If you are getting an error, what is the error?

Keith

**Comment by tetsuyacht** [comment]
I'm proposing that the example batch script on GitHub should be corrected.

**Comment by glasserm** [comment]
Sounds good.  Tim?
