### ISSUE TITLE
gradient nonlinear correction for non-Siemens scanners?

### ISSUE THREAD

**Issue by kjamison** [Washington-University/HCPpipelines#50]
Currently the GradientDistortionUnwarp.sh script has "siemens" hardcoded as the "vendor" input to gradient_unwarp.py.  It's straightforward enough to add an optional input to this script, and propagate that field up to other scripts, but has anyone tested whether this is all that's needed for GE scanners?

**Comment by glasserm** [comment]
I would assume not unless they use the same format for everything.  You may just have to give things a try and look at it.
