### ISSUE TITLE
Freesurfer v6 (dev version) optimization of recon-all for HCP data

### ISSUE THREAD

**Issue by ansk** [Washington-University/HCPpipelines#53]
Dear Timothy and other HCP experts,

I am currently in the process of setup and testing HCP pipelines with recent FreeSurfer dev version on our structural data acquired according to the parameters of HCP protocol. I was testing your `FreeSurferPipeline.sh` in https://github.com/Washington-University/Pipelines/tree/freesurfer_v6 branch
which calls `recon-all.v6.hires` script
https://github.com/freesurfer/freesurfer/blob/d26114a201333f812d2cef67a338e2685c004d00/scripts/recon-all.v6.hires
in 10 subjects against my optimized `recon-all` code and would like to share with you following observations:

1. You use resampled data to 1mm3 for tesselation. The reason is, as stated in the script, "If done in hires space, then there are lots of defects, and the topofixer sometimes cuts off a gyrus". However, experiences with my data are opposite. When I compared tesselation at 1mm3 and hires space, I saw that there are much more errors with data tesselated at 1mm3. With tess1mm in most subjects I found a spot where pial/white surface did not extent sufficienly outwards to cover all white/gray matter, in some subjects large portion of gyrus was cut off. The cut ouf of the gyrus in hires space occured in one spot in 2 subjects of 10, however in this case the error was present also in 1mm3 tesselation.
As an expamle, see several screenshots where 1mm3 tesselation cuts out a gyrus whereas hires tesselation is ok. 
hires tesselation: pial - yellow, white - red
1mm tesselation: pial - green, white - light blue

![tess1mm_issue_subj1](https://user-images.githubusercontent.com/10279434/34412334-f1491bc0-ebdc-11e7-844e-63c2c3b038e4.png)
![tess1mm_issue_subj2](https://user-images.githubusercontent.com/10279434/34412342-fc925488-ebdc-11e7-9359-6ef5f6f43c4c.png)
![tess1mm_issue_subj3](https://user-images.githubusercontent.com/10279434/34412344-00221f02-ebdd-11e7-80e8-a5f5f717175f.png)
![tess1mm_issue_subj4](https://user-images.githubusercontent.com/10279434/34412346-037f1e7a-ebdd-11e7-8640-5e37d1c5e563.png)

So, according to my testing, hires tesselation is better. Could you please comment on?

2. I presume that you use v6 version of FreeSurfer. There was substantial update of FLAIRpial/T2pial code in dev version. `-nsigma_above`, `-nsigma_below` parameters are considered obsolete, there are new parameters for T2/FLAIRpial ( `-T2_min_outside`, `-T2_max_outside`, `-T2_min_inside`, `-T2_min_outside`, `-wm_weight` and several others). 
See following commits:
https://github.com/freesurfer/freesurfer/commit/1fe83cd1a42c1f08b42e2f8f82521bb80d3466b3
https://github.com/freesurfer/freesurfer/commit/102e0539849e132ddd7933d74d06ca5d4137c2dd
https://github.com/freesurfer/freesurfer/commit/b4b47c85bb6ccdee0d246fd505f02e956bfae19a

Do you plan to update recon-all code to reflect these updates?

3. I think that `mris_inflate` with hires data has to have increased number of iterations (as also suggested here: https://surfer.nmr.mgh.harvard.edu/fswiki/SubmillimeterRecon ). I use `-n 50`.

4. you disabled `mri_normalize` for T2 (using `if (0)`) stating that it does not work well. Do you mean the errors whith artificially high intensities in T2 after normalization? There were some bugfixes in `mri_normalize` in dev version addressing that
(mainly following commit: https://github.com/freesurfer/freesurfer/commit/adb9cfda410a7a02bb2cceb435fcfdde6a76562a )
which maybe solves your issues?

There are another 3 points I encountered with processing of non-hires data but maybe also relevant here:

5. You use cubic interpolation for FLAIR/T2. In some other data I saw that cubic interpolation also for T1 leads to lesser smoothed T1 data and slight local improvement of gm/wm contrast. The cubic interpolation was default in patched version of 5.3, however, in v6.0, from reasons not clear to me, cubic is again switched off. With cubic interpolation off I had issues with local errors in white surface placement (white was extended too far out with artificially low thickness estimates) and these errors do not respond to editing of `wm.mgz`, so they were not correctable (apart from directly editing surface coordinates which is tedious and practically not usable). When I switched to cubic interpolation of T1, I got better response with surface placement on `wm.mgz` editing. The downside of that is that gm/wm interface is somewhat more noised and leads to higher amount of small errors which have to be corrected by more extensive `wm.mgz` editing. 
We partially discussed this with Bruce and Doug in following thread:
https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg52822.html
Did you do some testing with this option on HCP data? Do you have any experience with this?

6. In some subjects in the midline where cortex of left and right hemisphere touches, there was overlap of left and right pial surface. This overlap can be prevented using `aseg.presurf.mgz` in `mris_make_surfaces` in T2pial, but when aseg is incorrect in the midline (i.e. incorrectly assign voxel of left cortex to right cortex - which is often the case), this leads to artificial cut out portion of the gray matter. I solved this by running `recon-all` in 2 iterations: Firstly running standard `recon-all` (which used `aseg.presurf.mgz` in T2pial) and then rerun `recon-all -autorecon2-noaseg -autorecon3 -T2pial` but this time using `aseg.mgz` instead (which is generated by current surfaces almost in the end of the `recon-all`). This setup solved satisfactorily my issue. What do you think of this? Did you encounter similar issue with overlapping pial surfaces when testing recon-all on HCP data?

7. In some cases skullstrip is over-aggressive - cuts out small portions of gray matter. I found that the local issues with pial surface caused by this can be elegantly solved by following: Instead to use T2 masked by `brainmask.mgz` (or `brain.finalsurfs.mgz`, as is recommended in the recent dev version), I dilate the mask for T2 using `mri_binarize --dilate 2` to sligtly extend T2 image. T2pial then can correct for local small pial errors caused by local brainmask issue.

I am still in the process of optimizing things, so any comments on my proposals of code modification and your own view on the topic / open issues with `recon-all -hires` on HCP data will be very much appreciated.

Regards,

Antonin

**Comment by glasserm** [comment]
Hopefully Doug will be able to comment on this.  He did much of the tweaking of this pipeline to fix a list of issues we had identified with FS6.0.  These tweaks led to improvements so that 6.0 was more similar to 5.3.

Matt.

**Comment by ansk** [comment]
Dear @glasserm,
thank you for the feedback. I would very appreciate if Doug could comment on. Mainly the issue 1 is of a concern. My testing convinced me that `tess1mm` performance is inferior.

I would like to share two more things:
1. My testing shows that `mri_em_register` even with provided brain mask from PreFreeSurfer does its job poorly. This is maybe overlook since the `talairach.lta` output from `mri_em_register` is normally not QCed. But this inaccuracy propagates to following `mri_ca_normalize`, `mri_ca_register`, `mri_ca_label` and affects intensity normalization and GCA labeling which can have profound consequences.
MNI linear transform in PreFreeSurfer seems to be much better registration to MNI. 

2. Also the FreeSurfer's skullstrip performance is poor in comparison to skullstrip in PreFreeSurfer. This also affects intensity normalization, nonlinear registration in `mri_ca_register` and subsequent steps.

Would you consider to replace `talairach.lta` by MNI linear transform from PreFreeSurfer and/or replace `brainmask.mgz` by PreFreeSurfer's brain mask? 

Antonin

**Comment by tbbrown** [comment]
I don't think that Doug is set up to receive notifications of the comments in this thread. I have forwarded via email a link to this issue thread to Doug.

**Comment by dngreve** [comment]
Hi Antonin, I'll try to answer your questions:
1. Are those areas of defects that were incorrectly fixed and not some other error in surface placement? I found that the hires stream repeatedly had incorrectly fixed defects, so I'd be curious to see if yours are actually defects.
2. These do not include the dev version changes in the T2 stream as we wanted to use as much of v6 as possible. We have no plans to update to use the dev version. 
3. mris_inflate should work properly when the tessellation is done at 1mm. Are you seeing otherwise?
4. The v6 version of mri_normalize made the T2 pial placement much worse. I'm not sure I tried the dev version.
5. sorry, no experience with the interpolation issue. I can't remember why we did not turn on cubic interp for v6.
6. I have not noticed this issue.
7. I have not seen this issue, but your fix sounds good.

**Comment by glasserm** [comment]
5. I'm guessing cubic should be on as trilinear definitely created issues in the past when I had tested it.

**Comment by ansk** [comment]
Dear @dngreve ,

I very appreciate your comments. I tried to address it further:

1.  I think that it is a combination of undersampling of `filled.mgz` and incorrectly fixed defects in areas where 1mm3 resolution does not capture well the anatomy of thin white matter strains. See two examples of cutting of a gyrus:
 `recon-all.v6.hires` (with `tess1mm` tesselation), v6: `orig.nofix`, `white` and `pial`
![subj1_v6_tess1mm_1](https://user-images.githubusercontent.com/10279434/34695083-c10c02ce-f4c9-11e7-8710-3b350e6a856b.png)
 `recon-all.v6.hires` (with `tess1mm` tesselation),  v6: `orig` (i.e. after topology fixer), `white` and `pial`
![subj1_v6_tess1mm_2](https://user-images.githubusercontent.com/10279434/34695084-c1288c5a-f4c9-11e7-93dd-771761ea516e.png)
`recon-all` with hires tesselation, dev version: `orig.nofix`, `white` and `pial`
![subj1_dev_tesshires_1](https://user-images.githubusercontent.com/10279434/34695081-c0a304f4-f4c9-11e7-8016-4ac6f7f77151.png)
`recon-all` with hires tesselation, dev version: `orig`, `white` and `pial`
![subj1_dev_tesshires_2](https://user-images.githubusercontent.com/10279434/34695082-c0ca81aa-f4c9-11e7-9f7c-fd8b8be84bc1.png)
This is an example with serious cut of gyrus in temporal region:
 `recon-all.v6.hires` (with `tess1mm` tesselation),  v6: `orig.nofix`, `white` and `pial`
![subj4_v6_tess1mm_1](https://user-images.githubusercontent.com/10279434/34695088-c194d81a-f4c9-11e7-8a1d-6e74d262ace5.png)
 `recon-all.v6.hires` (with `tess1mm` tesselation),  v6: `orig` (i.e. after topology fixer), `white` and `pial`
![subj4_v6_tess1mm_2](https://user-images.githubusercontent.com/10279434/34695089-c1c37eb8-f4c9-11e7-938d-ca93e23b6415.png)
`recon-all` with hires tesselation, dev version: `orig.nofix`, `white` and `pial`
![subj4_dev_tesshires_1](https://user-images.githubusercontent.com/10279434/34695085-c14e58f4-f4c9-11e7-9660-a2f1b9e27115.png)
`recon-all` with hires tesselation, dev version: `orig`, `white` and `pial`
![subj4_dev_tesshires_2](https://user-images.githubusercontent.com/10279434/34695086-c17495b4-f4c9-11e7-8fcc-70f687785951.png)
The issue seems not to be based on difference between v6 version and dev version. The dev version with `tess1mm` cuts gyrus also in both example cases. 
In fact I think I did not see yet a spot where `tess1mm` was better than hires tesselation.

2. In my correspondence with Bruce I was in the impression that T2/FLAIR stuff in v6 is still in work-in-progress status. So I thought that using dev version for that could be of advantage that deserves implementation to the pipeline....Do you think that the T2/FLAIR changes in dev version are not mature enough to be used?

3. Sorry, I did not realize that all surfaces in tess1mm version have lower number of vertices, therefore no need to increase -n in `mris_inflate`.

4. OK

5. I think that the interpolation modes in T1 desire testing, they have profound effect.

6. I did not see this issue yet with v6 but there is an example how it can look like:
![pial_overlap](https://user-images.githubusercontent.com/10279434/34696914-e33d5738-f4d0-11e7-92a2-4e1501fbbee6.png)

7. OK

Antonin

**Comment by ansk** [comment]
For reference: Issue 1 has been caused by bug in `tess1mm` (spotted by #dngreve): `mri_pretess` was not run on right hemisphere.

**Comment by glasserm** [comment]
Thanks for reporting.  I think we did get a bugfix from Doug with this in it.
