### ISSUE TITLE
Consolidate PostFix functionality into ICAFIX?

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#54]
In the interest of simplifying the overall pipeline flow, I wonder if we couldn't consolidate the features of PostFix (which aren't very many) into the ICAFIX pipeline.

**Comment by glasserm** [comment]
I have suggested that in the past to Steve but it didn't happen...

**Comment by mharms** [comment]
I suspect that if someone at WU just made the necessary additions, that he wouldn't object.

**Comment by mharms** [comment]
`PostFix.sh` is now part of the ICAFIX directory, following a reorganization of all the FIX-related scripts into that directory.
