### ISSUE TITLE
Add example of running multi-run FIX

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#58]
Would be helpful if there was a template/batch script for multi-run FIX in Examples/Scripts.

**Comment by glasserm** [comment]
I have one locally.

**Comment by mchiu91** [comment]
Hello, I wasn’t sure if this question had been resolved- I can’t even to find an example script. Thank you!

**Comment by glasserm** [comment]
hcp_fix_multi_run ${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName1}/${fMRIName1}.nii.gz@${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRIName2}/${fMRIName2}.nii.gz@${StudyFolder}/${Subject}/MNINonLinear/Results/${fMRINameN}/${fMRINameN}.nii.gz 2000 ${StudyFolder}/${Subject}/MNINonLinear/Results/${ConcatName}/${ConcatName}.nii.gz

**Comment by glasserm** [comment]
e.g. fMRINames=tfMRI_WM_RL tfMRI_WM_LR tfMRI_GAMBLING_RL tfMRI_GAMBLING_LR tfMRI_MOTOR_RL tfMRI_MOTOR_LR 
becomes ConcatName=tfMRI_WM_GAMBLING_MOTOR_RL_LR
or 
fMRINames=tfMRI_LANGUAGE_RL tfMRI_LANGUAGE_LR tfMRI_SOCIAL_RL tfMRI_SOCIAL_LR tfMRI_RELATIONAL_RL tfMRI_RELATIONAL_LR tfMRI_EMOTION_RL tfMRI_EMOTION_LR"

becomes ConcatName=tfMRI_LANGUAGE_SOCIAL_RELATIONAL_EMOTION_RL_LR

**Comment by mchiu91** [comment]
I understand concatenating is helpful since the runs are so short but is it possible to use hcp_fix_multi_run on just one task (rather than 3) across both runs? 
fMRINames=tfMRI_GAMBLING_RL tfMRI_GAMBLING_LR

ConcatName=tfMRI_GAMBLING_RL_LR

Thank you very much! 

-Michelle

**Comment by glasserm** [comment]
Yes that would be possible though perhaps not optimal.

**Comment by mharms** [comment]
`Examples/Scripts/IcaFixProcessingBatch.sh` now supports launching of both single-run and multi-run FIX (thanks to @coalsont).  The comments therein are improved and hopefully sufficient for users.
