### ISSUE TITLE
In multi-run-fix, why copy individual run hp2000 files to 'filtered_func_data'

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#60]
What is the downstream purpose of this line:
https://github.com/Washington-University/Pipelines/blob/433f87866bfe6f61c60fd4e4a2d48389e4dd8e50/ICAFIX/hcp_fix_multi_run#L210

I can't figure it out, since the 'filtered_func_data' version of the file is not what gets merged.  Is it to simplify the application of some other downstream pipeline (e.g., RestingStateStats)?

**Comment by glasserm** [comment]
That may be used by FIX internally as it is not my name.

**Comment by mharms** [comment]
But we aren't actually running FIX on the individual runs.  FIX is run on the concatenated run, and the line in question is copying the _individual run_ ${task}_hp volume file to 'filtered_func_data', which seems irrelevant to 'hcp_fix_multi_run' itself.  So, I'm wondering if that line is a holdover from other code?  Unless a version of the individual run ${task}_hp volume file named as 'filtered_func_data' is actually necessary for some other downstream processing, that "copy" operation seems to be a waste of space.  (While it is structured as a "linking" operation, it inevitably ends up as a physical copy after data is transferred around).

**Comment by glasserm** [comment]
It may be unnecessary then.  I don't remember why it is there.

**Comment by mharms** [comment]
In that case (and it isn't used in RSS), should we just comment out that line?

**Comment by glasserm** [comment]
What about reapplyfix?

**Comment by mharms** [comment]
What is ReApplyFix for?  Is that for if there was a manual reclassification?  If so, wouldn't that have to be "reapplied" to the concatenated series?  Besides, L344 of ReApplyFix has its own internal `$FSLDIR/bin/imln ../$fmri filtered_func_data` anyway.

**Comment by glasserm** [comment]
We need to run ICA+FIX before MSMAll and then ReApply the cleanup after resampling from the native mesh timeseries again.

**Comment by mharms** [comment]
But doesn't that need to be done going back to the concatenated FIX-cleaned result.  I still don't see the purpose of this line creating a `filtered_func_data` file for the individual runs in `hcp_fix_multi_run`.

**Comment by glasserm** [comment]
it may not be needed.
