### ISSUE TITLE
Couldn't find T1w_hires.nii.gz with freesurfer 6

### ISSUE THREAD

**Issue by jokedurnez** [Washington-University/HCPpipelines#63]
Hi,

I'm running HCP pipelines on a dataset with freesurfer 6 and I'm running into an issue at [this line](https://github.com/Washington-University/Pipelines/blob/master/FreeSurfer/FreeSurferPipeline.sh#L328):

```
Mon Mar  5 06:21:10 UTC 2018 - FreeSurferPipeline.sh: cmd: fslmaths 
/oak/stanford/groups/russpold/data/Psychosis/0.0.3//derivatives/HCPPipelines/sub-S9905QEN/T1w/sub-S9905QEN/mri/T1w_hires.nii.gz -mul 
/oak/stanford/groups/russpold/data/Psychosis/0.0.3//derivatives/HCPPipelines/sub-S9905QEN/T1w/sub-S9905QEN/mri/T2w_hires.nii.gz -sqrt 
/oak/stanford/groups/russpold/data/Psychosis/0.0.3//derivatives/HCPPipelines/sub-S9905QEN/T1w/sub-S9905QEN/mri/T1wMulT2w_hires.nii.gz
```

I'm running the `freesurfer_v6`-branch.

Freesurfer had run succesfully, using the most recent [recon-all.v6.hires](https://raw.githubusercontent.com/freesurfer/freesurfer/dev/scripts/recon-all.v6.hires).

I've attached my freesurfer logs, as well as the pipeline logs.  
I tried to debug myself, but I can't find where in freesurfer the `T?w_hires.nii.gz` should be created.

Any thoughts?
[HCP pipelines log](https://github.com/Washington-University/Pipelines/files/1782327/prep_0_fs.out.txt)
[recon-all.cmd](https://github.com/Washington-University/Pipelines/files/1782329/recon-all.cmd.txt)
[recon-all-status.log](https://github.com/Washington-University/Pipelines/files/1782322/recon-all-status.log)
[recon-all.log](https://github.com/Washington-University/Pipelines/files/1782323/recon-all.log)

**Comment by glasserm** [comment]
The latest master has some issues in it as FreeSurfer v6.0 support is partly but not completely implemented yet.  I would recommend rolling back to FreeSurfer 5.3 at this time with a version of the pipelines before this support was added.  Tim Brown CCed can say which version that was.

Matt.

**Comment by mharms** [comment]
I'm closing this, as I assume it is no longer an issue.
