### ISSUE TITLE
PostFix.sh

### ISSUE THREAD

**Issue by tjhendrickson** [Washington-University/HCPpipelines#64]
I find the portion of the PostFix.sh code totally unintuitive:

	#if [ -e ${ComponentList} ] ; then
	#	log_Msg "Removing ComponentList: ${ComponentList}"
	#	rm ${ComponentList}
	#fi

1) Fix does not even generate this file, thus far as I can tell I have to generate it
2) Of course I do not want to edit PostFix.sh directly so I generate the ComponentList, Signal, and Noise text files in a separate PostFix control script
3) Unfortunately there is not way around the rm ${ComponentList}

What am I missing here?

**Comment by glasserm** [comment]
Have a look in the matlab code.  This file is created by prepareICAs and if it already exists it needs to be removed as it is created with a >> append command.
