### ISSUE TITLE
eddy non-gpu option

### ISSUE THREAD

**Issue by kjamison** [Washington-University/HCPpipelines#68]
There isn't a way to run the diffusion pipeline without a GPU currently.  `DiffusionPreprocessing/scripts/run_eddy.sh` has the capability to run eddy_openmp instead of eddy_cuda, but `DiffusionPreprocessing/DiffPreprocPipeline_Eddy.sh` is currently hard-coded to pass `run_eddy.sh` the "-g" flag.  Here's a patch that adds an optional "--eddy-non-gpu" argument to `DiffPreprocPipeline.sh`, passes it along to `DiffPreprocPipeline_Eddy.sh`, which then skips the "-g" argument when calling `run_eddy.sh`.  

I haven't thoroughly vetted it, so this is more of a suggestion/consideration.

[eddy_non_gpu.patch.zip](https://github.com/Washington-University/Pipelines/files/1992046/eddy_non_gpu.patch.zip)

**Comment by mharms** [comment]
Closing this issue, as @tbbrown made `DiffPreprocPipeline_Eddy.sh` more flexible in the recent past by adding `--no-gpu` and `--cuda-version` flags.  Admittedly, we didn't propagate this into a flag within the higher level calling script - `DiffPreprocPipeline.sh` - but adding the `--no-gpu` flag directly to the call to `DiffPreprocPipeline_Eddy.sh` is easy enough to do.
