### ISSUE TITLE
Rename repo to a less generic name

### ISSUE THREAD

**Issue by mharms** [Washington-University/HCPpipelines#71]
What do people think of renaming the repo to something more specific (e.g., `HCPpipelines`)?
According to this:
https://blog.github.com/2013-05-16-repository-redirects-are-here/
redirects are put in place that would make this completely transparent to end-users, although users can easily update the url of their local clone if they choose to do so, as described here:
https://help.github.com/articles/renaming-a-repository/

**Comment by beOn** [comment]
I like it.

**Comment by glasserm** [comment]
As long as old links work I don't really care.

**Comment by tbbrown** [comment]
Repository renamed to HCPpipelines.
All old links still should work.
