### ISSUE TITLE
Prefreesurfer "unwarpdir" parameter

### ISSUE THREAD

**Issue by dasturge** [Washington-University/HCPpipelines#75]
The unwarpdir parameter is described as the "readout direction" of the anatomical data (T1, T2) in the documentation for Prefreesurfer.  However, this parameter is ultimately passed into fsl fugue which describes unwarp direction as the phase encoding direction (for epi data).  Is there a difference between the acquisitions which would merit the perpendicular choice of unwarpdir?  Or is this possibly a mistake in documentation?

**Comment by glasserm** [comment]
3D acquisitions are distorted most in the readout direction.
