### ISSUE TITLE
Individual subject parcellation using HCP-MMP1.0 classifier

### ISSUE THREAD

**Issue by ellisdg** [Washington-University/HCPpipelines#84]
Has the areal classifier for individual subject parcellation ([Glasser et al. 2016](http://www.nature.com/nature/journal/vaop/ncurrent/full/nature18933.html)) been made available? As noted in the article:
> The MSMAll registration and the areal classifier are or will soon be freely available on GitHub

If not, is there some other way to obtain the individual parcellations for the HCP1200 data?

**Comment by glasserm** [comment]
MSMAll is available.  We hope to have the areal classifier available soon as a nice pipeline.

**Comment by DearBraveJohn** [comment]
Is the areal classifier available now?
