### ISSUE TITLE
Regarding PreFreeSurferPipeline

### ISSUE THREAD

**Issue by Sayan-2019** [Washington-University/HCPpipelines#91]
Hi...

I am new in this field. Trying to run the PreFreeSurferPipeline.sh but encountered the following error:

Images:  ./mystudy/102109/T1w/T1w1_gdc ./mystudy/102109/T1w/T1w2_gdc  Output: ./mystudy/102109/T1w/T1w

**ERROR: Could not find image ./mystudy/102109/T1w/AverageT1wImages/T1w1_gdc.nii.gz**

I found that the specified file (T1w1_gdc.nii.gz) is generated under T1w folder not under AverageT1wImages. 

Kindly help me in this regard. 

Thanks and Regards,

Sayan

**Comment by glasserm** [comment]
Please post your question on the hcp-users@humanconnectome.org together with exactly how you called the PreFreeSurfer pipeline in the Batch script.  

This forum is not really for user support, but rather for code development.
